# -*- coding: utf-8 -*-
"""
قائمة مصححة لمرادفات الألقاب والأسماء.

ملاحظات التصحيح:
- تم إصلاح خطأ الاقتباس في SID AHMED.
- تم دمج المفتاح المكرر ALI.
- تم حذف BENMOUMEN من BEN NOUNA لأنه تابع لـ BEN MOUMEN.
- تم حذف SSN_PATTERNS لأنها ليست من قائمة الألقاب.
- تم إضافة المفتاح نفسه كمرادف لكل مدخل ليساعد في المطابقة.

عند الاستيراد وفصل عمود "اللقب والاسم"، استعمل SURNAME_ALIAS_MAP أولًا
للبحث عن الألقاب المركبة من الأطول إلى الأقصر، ثم استعمل أول كلمة كحل احتياطي.
"""

ALIAS_MAP = {'ABDALLAH': ['ABDALLAH', 'عبد الله'],
 'ABDELHAMID': ['ABDELHAMID', 'عبد الحميد'],
 'ABDELKADER': ['ABDELKADER', 'عبد القادر', 'عبدالقادر', 'ABD EL KADER'],
 'ABDELLAOUI': ['ABDELLAOUI', 'عبد اللاوي'],
 'ABDERRAHMANE': ['ABDERRAHMANE', 'عبد الرحمن', 'عبدالرحمن', 'عبد الرحمان', 'ABDERAHMANE', 'ABD ERRAHMANE'],
 'AHMED': ['AHMED', 'احمد', 'أحمد', 'AHMAD'],
 'AICHA': ['AICHA', 'عائشة', 'عايشة', 'AICHE'],
 'AIT AHMED': ['AIT AHMED', 'ايت احمد', 'أيت أحمد'],
 'AIT HAMOU': ['AIT HAMOU', 'ايت حمو', 'أيت حمو', 'AIT HMOU', 'AYT HAMOU'],
 'AIT MOHAMED': ['AIT MOHAMED', 'ايت محمد', 'أيت محمد', 'AÏT MOHAMED', 'Aït Mohammed'],
 'ALI': ['ALI', 'علي'],
 'AMAR': ['AMAR', 'عمار', 'AMMAR'],
 'ALI BAI': ['ALI BAI', 'علي باي', 'ALIBAI'],
 'AÏT': ['AÏT', 'ايت'],
 'AÏT ABDELKADER': ['AÏT ABDELKADER', 'أيت عبد القادر'],
 'AÏT ABDERRAHMANE': ['AÏT ABDERRAHMANE', 'ايت عبد الرحمن'],
 'AÏT ALI': ['AÏT ALI', 'ايت علي'],
 'AÏT BEN MOUSSA': ['AÏT BEN MOUSSA', 'ايت بن موسى', 'Ait Ben Moussa'],
 'AÏT CHAÂLAL': ['AÏT CHAÂLAL', 'ايت شعلال'],
 'AÏT HAMDOUCHE': ['AÏT HAMDOUCHE', 'ايت حمدوش'],
 'AÏT HAMOU': ['AÏT HAMOU', 'أيت حمو'],
 'AÏT IMRANE': ['AÏT IMRANE', 'ايت عمران'],
 'AÏT MAÂMAR': ['AÏT MAÂMAR', 'ايت معمر'],
 'AÏT OMAR MEZIANE': ['AÏT OMAR MEZIANE', 'ايت عمر مزيان', 'Ait Omar Meziane', 'أيت عمر مزيان'],
 'AÏT SLIMANE': ['AÏT SLIMANE', 'ايت سليمان'],
 'BARK EL-LIL': ['BARK EL-LIL', 'برق الليل', 'برقليل'],
 'BELKACEM': ['BELKACEM', 'بلقاسم', 'BELKASSEM'],
 'BEN': ['BEN', 'بن'],
 'BEN ABD': ['BEN ABD', 'بن عبد'],
 'BEN ABDALLAH': ['BEN ABDALLAH', 'بن عبد الله'],
 'BEN ABDELKADER': ['BEN ABDELKADER', 'بن عبد القادر'],
 'BEN KIRAI': ['BEN KIRAI', 'بن كراي', 'Ben Karai'],
 'BEN ABDELKRIM': ['BEN ABDELKRIM', 'بن عبد الكريم'],
 'BEN ADJEROUDA': ['BEN ADJEROUDA', 'بن عجرودة'],
 'BEN AFIA': ['BEN AFIA', 'بن عافية'],
 'BEN AGROURBA': ['BEN AGROURBA', 'بن عقروبة'],
 'BEN ALI': ['BEN ALI', 'بن علي'],
 'BEN AMER': ['BEN AMER', 'بن عامر'],
 'BEN AMMAR': ['BEN AMMAR', 'بن عمار'],
 'BEN SRAYA': ['BEN SERAYA', 'بن صراية'],
 'BEN AOUDA': ['BEN AOUDA', 'بن عودة'],
 'BEN ARBI': ['BEN ARBI', 'بن العربي'],
 'BEN ARBIA': ['BEN ARBIA', 'بن عربية'],
 'BEN AÏSSA': ['BEN AÏSSA', 'بن عيسى'],
 'BEN CHAHRA': ['BEN CHAHRA', 'بن شهرة', 'بن شهره'],
 'BEN CHAÏB': ['BEN CHAÏB', 'بن شعيب'],
 'BEN CHBIRA': ['BEN CHBIRA', 'بن شبيرة'],
 'BEN CHERIF': ['BEN CHERIF', 'بن الشريف'],
 'BEN CHEÏB': ['BEN CHEÏB', 'بن الشيب'],
 'BEN CHIHIHA': ['BEN CHIHIHA', 'بن شيحة'],
 'BEN DAOUDI': ['BEN DAOUDI', 'بن داودي'],
 'BEN DJARRA': ['BEN DJARRA', 'بن جارة'],
 'BEN EL-AFIA': ['BEN EL-AFIA', 'بن العافية'],
 'BEN EL-ARABI': ['BEN EL-ARABI', 'بن العربية'],
 'BEN FERHAT': ['BEN FERHAT', 'بن فرحات'],
 'BEN GOUSHA': ['BEN GOUSHA', 'بن قوشة'],
 'BEN HABIB': ['BEN HABIB', 'بن حبيب'],
 'BEN HALIMA': ['BEN HALIMA', 'بن حليمة'],
 'BEN HAMDOUCHE': ['BEN HAMDOUCHE', 'بن حمدوش'],
 'BEN HAMMAM': ['BEN HAMMAM', 'بن همام'],
 'BEN HAOUCHE': ['BEN HAOUCHE', 'بن حاوش'],
 'BEN HENNI': ['BEN HENNI', 'بن هني'],
 'BEN HERANE': ['BEN HERANE', 'بن هران'],
 'BEN ISMAÏL': ['BEN ISMAÏL', 'بن اسماعيل', 'بن إسماعيل', 'Ben Ismail'],
 'BEN KAMEL': ['BEN KAMEL', 'بن كامل'],
 'BEN KAMLA': ['BEN KAMLA', 'بن كاملة', 'بن كملة'],
 'BEN KARIM': ['BEN KARIM', 'بن كريم'],
 'BEN KARIM ALLAH': ['BEN KARIM ALLAH', 'بن كريم الله'],
 'BEN MARIEM': ['BEN MARIEM', 'بن مريم'],
 'BEN MASSAOUD': ['BEN MASSAOUD', 'بن مسعود'],
 'BEN MAÏTI': ['BEN MAÏTI', 'بن مايتي'],
 'BEN MOHAMED': ['BEN MOHAMED', 'بن محمد'],
 'BEN MOUSSA': ['BEN MOUSSA', 'بن موسى'],
 'BEN NAQQACH': ['BEN NAQQACH', 'بن نقاش'],
 'BEN NAÂMAN': ['BEN NAÂMAN', 'بن نعمان'],
 'BEN NIF': ['BEN NIF', 'بن نيف'],
 'BEN NIFA': ['BEN NIFA', 'بن نيفة'],
 'BEN NÂAR': ['BEN NÂAR', 'بن نعار'],
 'BEN OMAR': ['BEN OMAR', 'بن عمر'],
 'BEN RAHIL': ['BEN RAHIL', 'بن راحيل'],
 'BEN SAADA': ['BEN SAADA', 'بن سعده'],
 'BEN SAFIA': ['BEN SAFIA', 'بن صفية'],
 'BEN SAÏD': ['BEN SAÏD', 'بن سعيد'],
 'BEN SEDDIK': ['BEN SEDDIK', 'بن صديق', 'بن الصديق'],
 'BEN SETRA': ['BEN SETRA', 'بن سترة'],
 'BEN SOUIH': ['BEN SOUIH', 'بن سويح'],
 'BEN TAAKA': ['BEN TAAKA', 'بن تقع', 'BEN TAKE'],
 'BEN TAMRA': ['BEN TAMRA', 'بن تمرة', 'بن تمره'],
 'BEN TATA': ['BEN TATA', 'بن طاطة', 'بن طاطا'],
 'BEN TORKIA': ['BEN TORKIA', 'بن تركية'],
 'BEN AZOUZ': ['BEN AZOUZ', 'بن عزوز'],
 'BEN ZETTA': ['BEN ZETTA', 'بن زطة', 'BEN ZETA', 'BENZETTA', 'BebZeta'],
 'BEN YAHIA': ['BEN YAHIA', 'بن يحيى'],
 'BEN YASSER': ['BEN YASSER', 'بن ياسر'],
 'BEN YATOU': ['BEN YATOU', 'بن يطو'],
 'BEN YOUNES': ['BEN YOUNES', 'بن يونس'],
 'BEN ZAYED': ['BEN ZAYED', 'بن زايد'],
 'BENT ELKHOUKHE': ['BENT ELKHOUKHE', 'بنت الخوخ', 'BENTELKHOUKHE', 'BENT ELKHOUKH', 'BentElkhoukh'],
 'BENT ALI': ['BENT ALI', 'بنت علي', 'BENTALI'],
 'BEN MOUMEN': ['BEN MOUMEN', 'بن مومن', 'BENMOUMEN', 'BEN MOUMENE', 'BENMOUMENE'],
 'BEN NOUNA': ['BEN NOUNA', 'بن نونة', 'BENNOUNA'],
 'BENT OMAR': ['BENT OMAR', 'بنت عمر', 'BENTOMAR'],
 'BEN ZERROUGUI': ['BEN ZERROUGUI', 'بن زروقي'],
 'BEN ZERROUGUE': ['BEN ZERROUGUE', 'بن زروق', 'Ben Zerrougu'],
 'BEN EDDINE': ['BEN EDDINE', 'بن الدين', 'Ben Edine'],
 'BEN IBRAHIM': ['BEN IBRAHIM', 'بن ابراهيم', 'بن إبراهيم', 'Ben Brahim'],
 'BENALI': ['BENALI', 'بن علي', 'BEN ALI'],
 'BENAMAR': ['BENAMAR', 'بن عمار', 'BEN AMAR'],
 'BOU ABD': ['BOU ABD', 'بو عبد'],
 'BOUAABIB': ['BOUAABIB', 'بوعبيب', 'بوعابيب', 'BOUABIB'],
 'BOUZIANE CHERIF': ['BOUZIANE CHERIF', 'بوزيان الشريف'],
 'CHAÂBANE CHAOUCH': ['CHAÂBANE CHAOUCH', 'شعبان شاوش'],
 'CHEBR': ['CHEBR', 'شبر', 'شابر'],
 'CHAOUNE': ['CHAOUNE', 'شعون', 'CHAAOUNE', 'CHAAOUN', 'CHAOUN', 'شاعون'],
 'DIB': ['DIB', 'ديب'],
 'DHIB': ['DHIB', 'ذيب'],
 'ELHADJ CHAÏB': ['ELHADJ CHAÏB', 'الحاج شعيب'],
 'FATIMA': ['FATIMA', 'فاطمة', 'فاطمه', 'FATMA'],
 'INES': ['INES', 'ايناس', 'إيناس', 'INESSE'],
 'KHADIDJA': ['KHADIDJA', 'خديجة', 'KHDIDJA'],
 'KHALED': ['KHALED', 'خالد'],
 'MEZIANE': ['MEZIANE', 'مزيان', 'MZIANE'],
 'MOHAMED': ['MOHAMED', 'محمد', 'محمّد', 'MOHAMMED', 'MUHAMMAD', 'MUHAMMED', 'MOHAMAD', 'MD'],
 'MOULAI ALI': ['MOULAI ALI', 'مولاي علي'],
 'MOHAMED CHERIF': ['MOHAMED CHERIF', 'محمد الشريف'],
 'OULD': ['OULD', 'ولد'],
 'OULD AMROUCHE': ['OULD AMROUCHE', 'ولد عمروش'],
 'OULD AMROUS': ['OULD AMROUS', 'ولد عمروس', 'ولد اعمروس', 'OULD AMRUS'],
 'OULD BASSI': ['OULD BASSI', 'ولد بسي'],
 'OULD KADDOUR': ['OULD KADDOUR', 'ولد قدور'],
 'OULD MOHAMED': ['OULD MOHAMED', 'ولد محمد'],
 'OULD SIDI': ['OULD SIDI', 'ولد سيدي'],
 'OULD SIDI MOHAMED': ['OULD SIDI MOHAMED', 'ولد سيدي محمد'],
 'OULD RABAH': ['OULD RABAH', 'ولد رابح', 'OULDRABAH'],
 'OULED': ['OULED', 'اولاد', 'أولاد', 'OULAD'],
 'RACHID': ['RACHID', 'رشيد', 'RACHIDE'],
 'RAS EL-MA': ['RAS EL-MA', 'راس الماء', 'راس الما'],
 'SEDDAR YAÂCOUB': ['SEDDAR YAÂCOUB', 'سدار يعقوب'],
 'SI BACHIR': ['SI BACHIR', 'سي بشير'],
 'SI TAYEB': ['SI TAYEB', 'سي الطيب'],
 'SID BOUH': ['SID BOUH', 'سيد بوح'],
 'SID AHMED': ['SID AHMED', 'سيد احمد', 'سيد أحمد'],
 'SAAD': ['SAAD', 'سعاد', 'Souad', 'Sad'],
 'YACINE': ['YACINE', 'ياسين', 'YASSINE'],
 'YOUCEF': ['YOUCEF', 'يوسف', 'YOUSSEF', 'Yossef'],
 'BEN YOUCEF': ['BEN YOUCEF', 'بن يوسف', 'BENYOUSSEF', 'Ben Yossef'],
 'AIT ALI': ['AIT ALI', 'ايت علي', 'أيت علي', 'AITALI'],
 'AIT MOUFEK': ['AIT MOUFEK', 'ايت موفق', 'أيت موفق', 'AITMOUFEK', 'AIT MUFEK', 'AITMUFEK'],
 'BEN KRIRA': ['BEN KRIRA', 'بن كريرة', 'BENKRIRA'],
 'ALI ISMAIL': ['ALI ISMAIL', 'علي إسماعيل'],
 'ATTALAH': ['ATTALAH', 'عطا الله', 'عطاالله', 'ATA LAH', 'ATTA LAH'],
 'BEN SALEM': ['BEN SALEM', 'بنسالم', 'بن سالم', 'BENSALEM'],
 'HAMOU SAID': ['HAMOSAID', 'حمو سعيد', 'HamouSaid', 'Hamou Said'],
 'BEN ABOUCHA': ['BEN ABOUCHA', 'بنعبوشة', 'بن عبوشة', 'BENABOUCHA']}

COMMON_GIVEN_NAME_KEYS = ['ABDALLAH',
 'ABDELHAMID',
 'ABDELKADER',
 'ABDERRAHMANE',
 'AHMED',
 'AICHA',
 'ALI',
 'AMAR',
 'FATIMA',
 'INES',
 'KHADIDJA',
 'KHALED',
 'MOHAMED',
 'MOHAMED CHERIF',
 'RACHID',
 'SAAD',
 'YACINE',
 'YOUCEF']

# هذه القائمة هي الأنسب للاستعمال عند فصل "اللقب والاسم" أثناء الاستيراد.
# استبعدنا منها الأسماء الشخصية الشائعة حتى لا تقسم الاسم الكامل بطريقة خاطئة.
SURNAME_ALIAS_MAP = {'ABDELLAOUI': ['ABDELLAOUI', 'عبد اللاوي'],
 'AIT AHMED': ['AIT AHMED', 'ايت احمد', 'أيت أحمد'],
 'AIT HAMOU': ['AIT HAMOU', 'ايت حمو', 'أيت حمو', 'AIT HMOU', 'AYT HAMOU'],
 'AIT MOHAMED': ['AIT MOHAMED', 'ايت محمد', 'أيت محمد', 'AÏT MOHAMED', 'Aït Mohammed'],
 'ALI BAI': ['ALI BAI', 'علي باي', 'ALIBAI'],
 'AÏT': ['AÏT', 'ايت'],
 'AÏT ABDELKADER': ['AÏT ABDELKADER', 'أيت عبد القادر'],
 'AÏT ABDERRAHMANE': ['AÏT ABDERRAHMANE', 'ايت عبد الرحمن'],
 'AÏT ALI': ['AÏT ALI', 'ايت علي'],
 'AÏT BEN MOUSSA': ['AÏT BEN MOUSSA', 'ايت بن موسى', 'Ait Ben Moussa'],
 'AÏT CHAÂLAL': ['AÏT CHAÂLAL', 'ايت شعلال'],
 'AÏT HAMDOUCHE': ['AÏT HAMDOUCHE', 'ايت حمدوش'],
 'AÏT HAMOU': ['AÏT HAMOU', 'أيت حمو'],
 'AÏT IMRANE': ['AÏT IMRANE', 'ايت عمران'],
 'AÏT MAÂMAR': ['AÏT MAÂMAR', 'ايت معمر'],
 'AÏT OMAR MEZIANE': ['AÏT OMAR MEZIANE', 'ايت عمر مزيان', 'Ait Omar Meziane', 'أيت عمر مزيان'],
 'AÏT SLIMANE': ['AÏT SLIMANE', 'ايت سليمان'],
 'BARK EL-LIL': ['BARK EL-LIL', 'برق الليل', 'برقليل'],
 'BELKACEM': ['BELKACEM', 'بلقاسم', 'BELKASSEM'],
 'BEN': ['BEN', 'بن'],
 'BEN ABD': ['BEN ABD', 'بن عبد'],
 'BEN ABDALLAH': ['BEN ABDALLAH', 'بن عبد الله'],
 'BEN ABDELKADER': ['BEN ABDELKADER', 'بن عبد القادر'],
 'BEN KIRAI': ['BEN KIRAI', 'بن كراي', 'Ben Karai'],
 'BEN ABDELKRIM': ['BEN ABDELKRIM', 'بن عبد الكريم'],
 'BEN ADJEROUDA': ['BEN ADJEROUDA', 'بن عجرودة'],
 'BEN AFIA': ['BEN AFIA', 'بن عافية'],
 'BEN AGROURBA': ['BEN AGROURBA', 'بن عقروبة'],
 'BEN ALI': ['BEN ALI', 'بن علي'],
 'BEN AMER': ['BEN AMER', 'بن عامر'],
 'BEN AMMAR': ['BEN AMMAR', 'بن عمار'],
 'BEN AOUDA': ['BEN AOUDA', 'بن عودة'],
 'BEN ARBI': ['BEN ARBI', 'بن العربي'],
 'BEN ARBIA': ['BEN ARBIA', 'بن عربية'],
 'BEN AÏSSA': ['BEN AÏSSA', 'بن عيسى'],
 'BEN CHAHRA': ['BEN CHAHRA', 'بن شهرة', 'بن شهره'],
 'BEN CHAÏB': ['BEN CHAÏB', 'بن شعيب'],
 'BEN CHBIRA': ['BEN CHBIRA', 'بن شبيرة'],
 'BEN CHERIF': ['BEN CHERIF', 'بن الشريف'],
 'BEN CHEÏB': ['BEN CHEÏB', 'بن الشيب'],
 'BEN CHIHIHA': ['BEN CHIHIHA', 'بن شيحة'],
 'BEN DAOUDI': ['BEN DAOUDI', 'بن داودي'],
 'BEN DJARRA': ['BEN DJARRA', 'بن جارة'],
 'BEN EL-AFIA': ['BEN EL-AFIA', 'بن العافية'],
 'BEN EL-ARABI': ['BEN EL-ARABI', 'بن العربية'],
 'BEN FERHAT': ['BEN FERHAT', 'بن فرحات'],
 'BEN GOUSHA': ['BEN GOUSHA', 'بن قوشة'],
 'BEN HABIB': ['BEN HABIB', 'بن حبيب'],
 'BEN HALIMA': ['BEN HALIMA', 'بن حليمة'],
 'BEN HAMDOUCHE': ['BEN HAMDOUCHE', 'بن حمدوش'],
 'BEN HAMMAM': ['BEN HAMMAM', 'بن همام'],
 'BEN HAOUCHE': ['BEN HAOUCHE', 'بن حاوش'],
 'BEN HENNI': ['BEN HENNI', 'بن هني'],
 'BEN HERANE': ['BEN HERANE', 'بن هران'],
 'BEN ISMAÏL': ['BEN ISMAÏL', 'بن اسماعيل', 'بن إسماعيل', 'Ben Ismail'],
 'BEN KAMEL': ['BEN KAMEL', 'بن كامل'],
 'BEN KAMLA': ['BEN KAMLA', 'بن كاملة', 'بن كملة'],
 'BEN KARIM': ['BEN KARIM', 'بن كريم'],
 'BEN KARIM ALLAH': ['BEN KARIM ALLAH', 'بن كريم الله'],
 'BEN MARIEM': ['BEN MARIEM', 'بن مريم'],
 'BEN MASSAOUD': ['BEN MASSAOUD', 'بن مسعود'],
 'BEN MAÏTI': ['BEN MAÏTI', 'بن مايتي'],
 'BEN MOHAMED': ['BEN MOHAMED', 'بن محمد'],
 'BEN MOUSSA': ['BEN MOUSSA', 'بن موسى'],
 'BEN NAQQACH': ['BEN NAQQACH', 'بن نقاش'],
 'BEN NAÂMAN': ['BEN NAÂMAN', 'بن نعمان'],
 'BEN NIF': ['BEN NIF', 'بن نيف'],
 'BEN NIFA': ['BEN NIFA', 'بن نيفة'],
 'BEN NÂAR': ['BEN NÂAR', 'بن نعار'],
 'BEN OMAR': ['BEN OMAR', 'بن عمر'],
 'BEN RAHIL': ['BEN RAHIL', 'بن راحيل'],
 'BEN SAADA': ['BEN SAADA', 'بن سعده'],
 'BEN SAFIA': ['BEN SAFIA', 'بن صفية'],
 'BEN SAÏD': ['BEN SAÏD', 'بن سعيد'],
 'BEN SEDDIK': ['BEN SEDDIK', 'بن صديق', 'بن الصديق'],
 'BEN SETRA': ['BEN SETRA', 'بن سترة'],
 'BEN SOUIH': ['BEN SOUIH', 'بن سويح'],
 'BEN TAAKA': ['BEN TAAKA', 'بن تقع', 'BEN TAKE'],
 'BEN TAMRA': ['BEN TAMRA', 'بن تمرة', 'بن تمره'],
 'BEN TATA': ['BEN TATA', 'بن طاطة', 'بن طاطا'],
 'BEN TORKIA': ['BEN TORKIA', 'بن تركية'],
 'BEN AZOUZ': ['BEN AZOUZ', 'بن عزوز'],
 'BEN ZETTA': ['BEN ZETTA', 'بن زطة', 'BEN ZETA', 'BENZETTA', 'BebZeta'],
 'BEN YAHIA': ['BEN YAHIA', 'بن يحيى'],
 'BEN YASSER': ['BEN YASSER', 'بن ياسر'],
 'BEN YATOU': ['BEN YATOU', 'بن يطو'],
 'BEN YOUNES': ['BEN YOUNES', 'بن يونس'],
 'BEN ZAYED': ['BEN ZAYED', 'بن زايد'],
 'BENT ELKHOUKHE': ['BENT ELKHOUKHE', 'بنت الخوخ', 'BENTELKHOUKHE', 'BENT ELKHOUKH', 'BentElkhoukh'],
 'BENT ALI': ['BENT ALI', 'بنت علي', 'BENTALI'],
 'BEN MOUMEN': ['BEN MOUMEN', 'بن مومن', 'BENMOUMEN', 'BEN MOUMENE', 'BENMOUMENE'],
 'BEN NOUNA': ['BEN NOUNA', 'بن نونة', 'BENNOUNA'],
 'BENT OMAR': ['BENT OMAR', 'بنت عمر', 'BENTOMAR'],
 'BEN ZERROUGUI': ['BEN ZERROUGUI', 'بن زروقي'],
 'BEN ZERROUGUE': ['BEN ZERROUGUE', 'بن زروق', 'Ben Zerrougu'],
 'BEN EDDINE': ['BEN EDDINE', 'بن الدين', 'Ben Edine'],
 'BEN IBRAHIM': ['BEN IBRAHIM', 'بن ابراهيم', 'بن إبراهيم', 'Ben Brahim'],
 'BENALI': ['BENALI', 'بن علي', 'BEN ALI'],
 'BENAMAR': ['BENAMAR', 'بن عمار', 'BEN AMAR'],
 'BOU ABD': ['BOU ABD', 'بو عبد'],
 'BOUAABIB': ['BOUAABIB', 'بوعبيب', 'بوعابيب', 'BOUABIB'],
 'BOUZIANE CHERIF': ['BOUZIANE CHERIF', 'بوزيان الشريف'],
 'CHAÂBANE CHAOUCH': ['CHAÂBANE CHAOUCH', 'شعبان شاوش'],
 'CHEBR': ['CHEBR', 'شبر', 'شابر'],
 'CHAOUNE': ['CHAOUNE', 'شعون', 'CHAAOUNE', 'CHAAOUN', 'CHAOUN', 'شاعون'],
 'DIB': ['DIB', 'ديب'],
 'DHIB': ['DHIB', 'ذيب'],
 'ELHADJ CHAÏB': ['ELHADJ CHAÏB', 'الحاج شعيب'],
 'MEZIANE': ['MEZIANE', 'مزيان', 'MZIANE'],
 'MOULAI ALI': ['MOULAI ALI', 'مولاي علي'],
 'OULD': ['OULD', 'ولد'],
 'OULD AMROUCHE': ['OULD AMROUCHE', 'ولد عمروش'],
 'OULD AMROUS': ['OULD AMROUS', 'ولد عمروس', 'ولد اعمروس', 'OULD AMRUS'],
 'OULD BASSI': ['OULD BASSI', 'ولد بسي'],
 'OULD KADDOUR': ['OULD KADDOUR', 'ولد قدور'],
 'OULD MOHAMED': ['OULD MOHAMED', 'ولد محمد'],
 'OULD SIDI': ['OULD SIDI', 'ولد سيدي'],
 'OULD SIDI MOHAMED': ['OULD SIDI MOHAMED', 'ولد سيدي محمد'],
 'OULD RABAH': ['OULD RABAH', 'ولد رابح', 'OULDRABAH'],
 'OULED': ['OULED', 'اولاد', 'أولاد', 'OULAD'],
 'RAS EL-MA': ['RAS EL-MA', 'راس الماء', 'راس الما'],
 'SEDDAR YAÂCOUB': ['SEDDAR YAÂCOUB', 'سدار يعقوب'],
 'SI BACHIR': ['SI BACHIR', 'سي بشير'],
 'SI TAYEB': ['SI TAYEB', 'سي الطيب'],
 'SID BOUH': ['SID BOUH', 'سيد بوح'],
 'SID AHMED': ['SID AHMED', 'سيد احمد', 'سيد أحمد'],
 'BEN YOUCEF': ['BEN YOUCEF', 'بن يوسف', 'BENYOUSSEF', 'Ben Yossef'],
 'AIT ALI': ['AIT ALI', 'ايت علي', 'أيت علي', 'AITALI'],
 'AIT MOUFEK': ['AIT MOUFEK', 'ايت موفق', 'أيت موفق', 'AITMOUFEK', 'AIT MUFEK', 'AITMUFEK'],
 'BEN KRIRA': ['BEN KRIRA', 'بن كريرة', 'BENKRIRA'],
 'ALI ISMAIL': ['ALI ISMAIL', 'علي إسماعيل'],
 'ATTALAH': ['ATTALAH', 'عطا الله', 'عطاالله', 'ATA LAH', 'ATTA LAH'],
 'BEN SALEM': ['BEN SALEM', 'بنسالم', 'بن سالم', 'BENSALEM'],
 'BEN ABOUCHA': ['BEN ABOUCHA', 'بنعبوشة', 'بن عبوشة', 'BENABOUCHA']}

# احتفظنا بهذه الأسماء للاستعمال لاحقًا في التطبيع أو المطابقة، لكنها ليست الخيار الأول لفصل اللقب.
GIVEN_NAME_ALIAS_MAP = {'ABDALLAH': ['ABDALLAH', 'عبد الله'],
 'ABDELHAMID': ['ABDELHAMID', 'عبد الحميد'],
 'ABDELKADER': ['ABDELKADER', 'عبد القادر', 'عبدالقادر', 'ABD EL KADER'],
 'ABDERRAHMANE': ['ABDERRAHMANE', 'عبد الرحمن', 'عبدالرحمن', 'ABDERAHMANE', 'ABD ERRAHMANE'],
 'AHMED': ['AHMED', 'احمد', 'أحمد', 'AHMAD'],
 'AICHA': ['AICHA', 'عائشة', 'عايشة', 'AICHE'],
 'ALI': ['ALI', 'علي'],
 'AMAR': ['AMAR', 'عمار', 'AMMAR'],
 'FATIMA': ['FATIMA', 'فاطمة', 'فاطمه', 'FATMA'],
 'INES': ['INES', 'ايناس', 'إيناس', 'INESSE'],
 'KHADIDJA': ['KHADIDJA', 'خديجة', 'KHDIDJA'],
 'KHALED': ['KHALED', 'خالد'],
 'MOHAMED': ['MOHAMED', 'محمد', 'محمّد', 'MOHAMMED', 'MUHAMMAD', 'MUHAMMED', 'MOHAMAD', 'MD'],
 'MOHAMED CHERIF': ['MOHAMED CHERIF', 'محمد الشريف'],
 'RACHID': ['RACHID', 'رشيد', 'RACHIDE'],
 'SAAD': ['SAAD', 'سعاد', 'Souad', 'Sad'],
 'YACINE': ['YACINE', 'ياسين', 'YASSINE'],
 'YOUCEF': ['YOUCEF', 'يوسف', 'YOUSSEF', 'Yossef']}

