# Clean initial migration for sync_core.
# This migration replaces the earlier phase-by-phase experimental migrations
# so a fresh installation creates the final sync tables exactly once.

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OfficeIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("mode", models.CharField(choices=[("local_office", "خادم مكتب محلي"), ("central_server", "خادم مركزي")], default="local_office", max_length=30, verbose_name="نمط التشغيل")),
                ("office_id", models.CharField(max_length=80, unique=True, verbose_name="معرف المكتب")),
                ("office_name", models.CharField(blank=True, max_length=150, verbose_name="اسم المكتب")),
                ("server_id", models.CharField(max_length=80, unique=True, verbose_name="معرف خادم المكتب")),
                ("central_url", models.URLField(blank=True, verbose_name="رابط الخادم المركزي")),
                ("sync_token", models.CharField(blank=True, max_length=255, verbose_name="رمز المزامنة")),
                ("sync_enabled", models.BooleanField(default=False, verbose_name="تفعيل الاتصال بالخادم المركزي")),
                ("last_checked_at", models.DateTimeField(blank=True, null=True, verbose_name="آخر فحص")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تعديل")),
            ],
            options={
                "verbose_name": "هوية المزامنة للمكتب",
                "verbose_name_plural": "هوية المزامنة للمكتب",
            },
        ),
        migrations.CreateModel(
            name="SyncState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("direction", models.CharField(choices=[("push", "إرسال"), ("pull", "استقبال")], max_length=20, verbose_name="الاتجاه")),
                ("scope", models.CharField(default="global", max_length=120, verbose_name="النطاق")),
                ("last_cursor", models.CharField(blank=True, max_length=200, verbose_name="آخر مؤشر")),
                ("last_event_at", models.DateTimeField(blank=True, null=True, verbose_name="وقت آخر حدث")),
                ("last_success_at", models.DateTimeField(blank=True, null=True, verbose_name="آخر نجاح")),
                ("last_error_at", models.DateTimeField(blank=True, null=True, verbose_name="آخر خطأ")),
                ("last_error", models.TextField(blank=True, verbose_name="نص آخر خطأ")),
                ("extra", models.JSONField(blank=True, default=dict, verbose_name="معلومات إضافية")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
            ],
            options={
                "verbose_name": "حالة المزامنة",
                "verbose_name_plural": "حالات المزامنة",
                "ordering": ["direction", "scope"],
                "unique_together": {("direction", "scope")},
            },
        ),
        migrations.CreateModel(
            name="SyncOutbox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="معرف الحدث")),
                ("office_id", models.CharField(max_length=80, verbose_name="معرف المكتب")),
                ("server_id", models.CharField(max_length=80, verbose_name="معرف الخادم")),
                ("app_label", models.CharField(max_length=100, verbose_name="التطبيق")),
                ("model_name", models.CharField(max_length=100, verbose_name="النموذج")),
                ("object_pk", models.CharField(max_length=200, verbose_name="معرف السجل")),
                ("operation", models.CharField(choices=[("create", "إنشاء"), ("update", "تعديل"), ("delete", "حذف"), ("snapshot", "لقطة")], max_length=20, verbose_name="نوع العملية")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="البيانات")),
                ("changed_fields", models.JSONField(blank=True, default=list, verbose_name="الحقول المعدلة")),
                ("payload_hash", models.CharField(blank=True, max_length=64, verbose_name="بصمة البيانات")),
                ("idempotency_key", models.CharField(max_length=220, unique=True, verbose_name="مفتاح منع التكرار")),
                ("status", models.CharField(choices=[("pending", "ينتظر الإرسال"), ("sending", "قيد الإرسال"), ("sent", "تم الإرسال"), ("failed", "فشل"), ("skipped", "متجاوز")], default="pending", max_length=20, verbose_name="الحالة")),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="عدد المحاولات")),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True, verbose_name="آخر محاولة")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="وقت الإرسال")),
                ("error_message", models.TextField(blank=True, verbose_name="رسالة الخطأ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
            ],
            options={
                "verbose_name": "صندوق الإرسال",
                "verbose_name_plural": "صندوق الإرسال",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncInbox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField(unique=True, verbose_name="معرف الحدث")),
                ("source_office_id", models.CharField(max_length=80, verbose_name="المكتب المصدر")),
                ("source_server_id", models.CharField(blank=True, max_length=80, verbose_name="الخادم المصدر")),
                ("app_label", models.CharField(max_length=100, verbose_name="التطبيق")),
                ("model_name", models.CharField(max_length=100, verbose_name="النموذج")),
                ("object_pk", models.CharField(max_length=200, verbose_name="معرف السجل")),
                ("operation", models.CharField(max_length=20, verbose_name="نوع العملية")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="البيانات")),
                ("central_cursor", models.CharField(blank=True, max_length=200, verbose_name="مؤشر الخادم المركزي")),
                ("status", models.CharField(choices=[("received", "تم الاستقبال"), ("applied", "تم التطبيق"), ("conflict", "تعارض"), ("failed", "فشل"), ("ignored", "متجاهل")], default="received", max_length=20, verbose_name="الحالة")),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="وقت الاستقبال")),
                ("applied_at", models.DateTimeField(blank=True, null=True, verbose_name="وقت التطبيق")),
                ("error_message", models.TextField(blank=True, verbose_name="رسالة الخطأ")),
            ],
            options={
                "verbose_name": "صندوق الاستقبال",
                "verbose_name_plural": "صندوق الاستقبال",
                "ordering": ["received_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("conflict_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="معرف التعارض")),
                ("app_label", models.CharField(max_length=100, verbose_name="التطبيق")),
                ("model_name", models.CharField(max_length=100, verbose_name="النموذج")),
                ("object_pk", models.CharField(max_length=200, verbose_name="معرف السجل")),
                ("local_event_id", models.UUIDField(blank=True, null=True, verbose_name="حدث محلي")),
                ("remote_event_id", models.UUIDField(blank=True, null=True, verbose_name="حدث بعيد")),
                ("reason", models.CharField(max_length=200, verbose_name="السبب")),
                ("local_payload", models.JSONField(blank=True, default=dict, verbose_name="البيانات المحلية")),
                ("remote_payload", models.JSONField(blank=True, default=dict, verbose_name="البيانات البعيدة")),
                ("resolution", models.TextField(blank=True, verbose_name="طريقة الحل")),
                ("status", models.CharField(choices=[("open", "مفتوح"), ("resolved", "محلول"), ("ignored", "متجاهل")], default="open", max_length=20, verbose_name="الحالة")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="تاريخ الحل")),
            ],
            options={
                "verbose_name": "تعارض مزامنة",
                "verbose_name_plural": "تعارضات المزامنة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CentralOffice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("office_id", models.CharField(max_length=80, unique=True, verbose_name="معرف المكتب")),
                ("office_name", models.CharField(blank=True, max_length=150, verbose_name="اسم المكتب")),
                ("server_id", models.CharField(blank=True, max_length=80, verbose_name="معرف آخر خادم")),
                ("sync_token", models.CharField(max_length=255, verbose_name="رمز المزامنة")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                ("allow_push", models.BooleanField(default=True, verbose_name="السماح بالإرسال")),
                ("allow_pull", models.BooleanField(default=True, verbose_name="السماح بالاستقبال")),
                ("license_status", models.CharField(choices=[("active", "نشط"), ("trial", ""), ("expired", "منتهي"), ("suspended", "موقوف")], default="active", max_length=40, verbose_name="حالة الترخيص")),
                ("license_expires_at", models.DateField(blank=True, null=True, verbose_name="انتهاء الترخيص")),
                ("license_plan", models.CharField(blank=True, default="standard", max_length=80, verbose_name="نوع الترخيص")),
                ("max_users", models.PositiveIntegerField(default=5, verbose_name="عدد المستخدمين المسموح")),
                ("feature_flags", models.JSONField(blank=True, default=dict, verbose_name="الخصائص المفعلة")),
                ("disabled_reason", models.TextField(blank=True, verbose_name="سبب التعطيل")),
                ("control_notes", models.TextField(blank=True, verbose_name="ملاحظات المطور")),
                ("last_seen_at", models.DateTimeField(blank=True, null=True, verbose_name="آخر اتصال")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ التسجيل")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
            ],
            options={
                "verbose_name": "مكتب مركزي",
                "verbose_name_plural": "المكاتب المركزية",
                "ordering": ["office_id"],
            },
        ),
        migrations.CreateModel(
            name="CentralSyncEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("central_event_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="معرف مركزي")),
                ("source_event_id", models.UUIDField(unique=True, verbose_name="معرف الحدث الأصلي")),
                ("source_office_id", models.CharField(max_length=80, verbose_name="المكتب المصدر")),
                ("source_server_id", models.CharField(blank=True, max_length=80, verbose_name="الخادم المصدر")),
                ("app_label", models.CharField(max_length=100, verbose_name="التطبيق")),
                ("model_name", models.CharField(max_length=100, verbose_name="النموذج")),
                ("object_pk", models.CharField(max_length=200, verbose_name="معرف السجل")),
                ("operation", models.CharField(max_length=20, verbose_name="نوع العملية")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="البيانات")),
                ("changed_fields", models.JSONField(blank=True, default=list, verbose_name="الحقول المعدلة")),
                ("payload_hash", models.CharField(blank=True, max_length=64, verbose_name="بصمة البيانات")),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="وقت الاستقبال المركزي")),
                ("source_created_at", models.DateTimeField(blank=True, null=True, verbose_name="وقت إنشاء الحدث في المكتب")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="محذوف منطقيًا")),
                ("extra", models.JSONField(blank=True, default=dict, verbose_name="معلومات إضافية")),
            ],
            options={
                "verbose_name": "حدث مزامنة مركزي",
                "verbose_name_plural": "أحداث المزامنة المركزية",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CentralUpdateRelease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=50, unique=True, verbose_name="رقم النسخة")),
                ("title", models.CharField(blank=True, max_length=180, verbose_name="عنوان التحديث")),
                ("channel", models.CharField(choices=[("stable", "مستقر"), ("test", "")], default="stable", max_length=30, verbose_name="القناة")),
                ("update_type", models.CharField(choices=[("installer", "Installer كامل"), ("patch", "Patch ملفات معدلة")], default="patch", max_length=30, verbose_name="نوع التحديث")),
                ("download_url", models.URLField(blank=True, verbose_name="رابط التحميل")),
                ("checksum_sha256", models.CharField(blank=True, max_length=64, verbose_name="SHA256")),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True, verbose_name="حجم الملف بالبايت")),
                ("release_notes", models.TextField(blank=True, verbose_name="ملاحظات الإصدار")),
                ("is_active", models.BooleanField(default=False, verbose_name="منشور")),
                ("is_required", models.BooleanField(default=False, verbose_name="تحديث إجباري")),
                ("rollout_all_offices", models.BooleanField(default=True, verbose_name="إرسال لكل المكاتب")),
                ("allowed_office_ids", models.JSONField(blank=True, default=list, verbose_name="المكاتب المسموحة")),
                ("blocked_office_ids", models.JSONField(blank=True, default=list, verbose_name="المكاتب المحظورة")),
                ("min_current_version", models.CharField(blank=True, max_length=50, verbose_name="أقل نسخة مسموح تحديثها")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="تاريخ النشر")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
            ],
            options={
                "verbose_name": "إصدار تحديث مركزي",
                "verbose_name_plural": "إصدارات التحديثات المركزية",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CentralUpdateCheckLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("office_id", models.CharField(max_length=80, verbose_name="معرف المكتب")),
                ("server_id", models.CharField(blank=True, max_length=80, verbose_name="معرف الخادم")),
                ("current_version", models.CharField(blank=True, max_length=50, verbose_name="النسخة الحالية")),
                ("channel", models.CharField(blank=True, max_length=30, verbose_name="قناة التحديث")),
                ("offered_version", models.CharField(blank=True, max_length=50, verbose_name="النسخة المعروضة")),
                ("has_update", models.BooleanField(default=False, verbose_name="يوجد تحديث")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="عنوان IP")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="وقت الفحص")),
                ("office_ref", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="update_checks", to="sync_core.centraloffice", verbose_name="المكتب المركزي")),
            ],
            options={
                "verbose_name": "سجل فحص تحديث",
                "verbose_name_plural": "سجل فحص التحديثات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(model_name="syncoutbox", index=models.Index(fields=["status", "created_at"], name="sync_outbox_status_created")),
        migrations.AddIndex(model_name="syncoutbox", index=models.Index(fields=["app_label", "model_name", "object_pk"], name="sync_outbox_object")),
        migrations.AddIndex(model_name="syncoutbox", index=models.Index(fields=["office_id", "server_id"], name="sync_outbox_office_server")),
        migrations.AddIndex(model_name="syncinbox", index=models.Index(fields=["status", "received_at"], name="sync_inbox_status_received")),
        migrations.AddIndex(model_name="syncinbox", index=models.Index(fields=["app_label", "model_name", "object_pk"], name="sync_inbox_object")),
        migrations.AddIndex(model_name="syncinbox", index=models.Index(fields=["source_office_id", "source_server_id"], name="sync_inbox_source")),
        migrations.AddIndex(model_name="syncconflict", index=models.Index(fields=["status", "created_at"], name="sync_conflict_status")),
        migrations.AddIndex(model_name="syncconflict", index=models.Index(fields=["app_label", "model_name", "object_pk"], name="sync_conflict_object")),
        migrations.AddIndex(model_name="centralsyncevent", index=models.Index(fields=["id"], name="central_event_id_idx")),
        migrations.AddIndex(model_name="centralsyncevent", index=models.Index(fields=["source_office_id", "source_server_id"], name="central_event_office_server")),
        migrations.AddIndex(model_name="centralsyncevent", index=models.Index(fields=["app_label", "model_name", "object_pk"], name="central_event_object")),
        migrations.AddIndex(model_name="centralsyncevent", index=models.Index(fields=["received_at"], name="central_event_received")),
        migrations.AddIndex(model_name="centralupdatechecklog", index=models.Index(fields=["office_id", "created_at"], name="central_update_office_time")),
        migrations.AddIndex(model_name="centralupdatechecklog", index=models.Index(fields=["has_update", "created_at"], name="central_update_has_time")),
    ]
