# Generated by Django 5.2.14 on 2026-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_core', '0004_central_update_local_package'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='centralsyncevent',
            new_name='sync_core_c_id_fbe6dd_idx',
            old_name='central_event_id_idx',
        ),
        migrations.RenameIndex(
            model_name='centralsyncevent',
            new_name='sync_core_c_source__9fb2f1_idx',
            old_name='central_event_office_server',
        ),
        migrations.RenameIndex(
            model_name='centralsyncevent',
            new_name='sync_core_c_app_lab_70c7c8_idx',
            old_name='central_event_object',
        ),
        migrations.RenameIndex(
            model_name='centralsyncevent',
            new_name='sync_core_c_receive_d6e95e_idx',
            old_name='central_event_received',
        ),
        migrations.RenameIndex(
            model_name='centralupdatechecklog',
            new_name='sync_core_c_office__ead626_idx',
            old_name='central_update_office_time',
        ),
        migrations.RenameIndex(
            model_name='centralupdatechecklog',
            new_name='sync_core_c_has_upd_4b7ffb_idx',
            old_name='central_update_has_time',
        ),
        migrations.RenameIndex(
            model_name='syncconflict',
            new_name='sync_core_s_status_b6e899_idx',
            old_name='sync_conflict_status',
        ),
        migrations.RenameIndex(
            model_name='syncconflict',
            new_name='sync_core_s_app_lab_304a9c_idx',
            old_name='sync_conflict_object',
        ),
        migrations.RenameIndex(
            model_name='syncinbox',
            new_name='sync_core_s_status_e6af88_idx',
            old_name='sync_inbox_status_received',
        ),
        migrations.RenameIndex(
            model_name='syncinbox',
            new_name='sync_core_s_app_lab_3df2e7_idx',
            old_name='sync_inbox_object',
        ),
        migrations.RenameIndex(
            model_name='syncinbox',
            new_name='sync_core_s_source__c006ad_idx',
            old_name='sync_inbox_source',
        ),
        migrations.RenameIndex(
            model_name='syncoutbox',
            new_name='sync_core_s_status_223f25_idx',
            old_name='sync_outbox_status_created',
        ),
        migrations.RenameIndex(
            model_name='syncoutbox',
            new_name='sync_core_s_app_lab_585fcb_idx',
            old_name='sync_outbox_object',
        ),
        migrations.RenameIndex(
            model_name='syncoutbox',
            new_name='sync_core_s_office__f8eae3_idx',
            old_name='sync_outbox_office_server',
        ),
        migrations.AlterField(
            model_name='centralupdaterelease',
            name='download_url',
            field=models.URLField(blank=True, verbose_name='رابط التحميل الخارجي'),
        ),
    ]
