# Generated by ChatGPT on 2026-07-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_core', '0005_rename_central_event_id_idx_sync_core_c_id_fbe6dd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='كود الولاية')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الولاية بالعربية')),
                ('name_latin', models.CharField(blank=True, max_length=120, verbose_name='الولاية باللاتينية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'ولاية',
                'verbose_name_plural': 'الولايات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='كود البلدية')),
                ('name_ar', models.CharField(max_length=160, verbose_name='البلدية بالعربية')),
                ('name_latin', models.CharField(blank=True, max_length=160, verbose_name='البلدية باللاتينية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='sync_core.wilaya', verbose_name='الولاية')),
            ],
            options={
                'verbose_name': 'بلدية',
                'verbose_name_plural': 'البلديات',
                'ordering': ['wilaya__code', 'code'],
            },
        ),
        migrations.AddField(
            model_name='centraloffice',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='sync_core.commune', verbose_name='البلدية'),
        ),
        migrations.AddField(
            model_name='centraloffice',
            name='establishment_number',
            field=models.CharField(blank=True, default='01', help_text='يبقى نصًا مثل 01 أو 02 حتى لا يضيع الصفر.', max_length=4, verbose_name='رقم المؤسسة داخل البلدية'),
        ),
        migrations.AddField(
            model_name='centraloffice',
            name='establishment_type',
            field=models.CharField(blank=True, choices=[('INSFP', 'معهد وطني متخصص INSFP'), ('CFPA', 'مركز التكوين المهني والتمهين CFPA'), ('ANNEXE', 'ملحقة ANNEXE'), ('DIRECTION', 'مديرية / إدارة DIRECTION'), ('OTHER', 'أخرى')], default='', max_length=30, verbose_name='نوع المؤسسة'),
        ),
        migrations.AddField(
            model_name='centraloffice',
            name='office_alias',
            field=models.CharField(blank=True, help_text='مثال: DZ38-TIS-INSFP01', max_length=60, verbose_name='اختصار بشري للمؤسسة'),
        ),
        migrations.AddField(
            model_name='centraloffice',
            name='office_code',
            field=models.CharField(blank=True, db_index=True, help_text='مثال: DZ38-03801-INSFP01', max_length=40, null=True, unique=True, verbose_name='الكود الرسمي للمؤسسة'),
        ),
        migrations.AddField(
            model_name='centraloffice',
            name='office_display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='الاسم الرسمي الظاهر للمؤسسة'),
        ),
        migrations.AddField(
            model_name='centraloffice',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='sync_core.wilaya', verbose_name='الولاية'),
        ),
        migrations.AlterModelOptions(
            name='centraloffice',
            options={'ordering': ['office_code', 'office_id'], 'verbose_name': 'مكتب مركزي', 'verbose_name_plural': 'المكاتب المركزية'},
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=80, verbose_name='كود الوحدة')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الوحدة بالعربية')),
                ('unit_type', models.CharField(choices=[('general', 'إدارة عامة'), ('subdirectorate', 'مديرية فرعية'), ('service', 'مصلحة'), ('position', 'منصب / مسؤولية')], default='service', max_length=30, verbose_name='نوع الوحدة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_units', to='sync_core.centraloffice', verbose_name='المؤسسة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sync_core.organizationunit', verbose_name='الوحدة الأب')),
            ],
            options={
                'verbose_name': 'وحدة إدارية',
                'verbose_name_plural': 'الوحدات الإدارية',
                'ordering': ['office__office_code', 'order', 'id'],
                'unique_together': {('office', 'unit_code')},
            },
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['wilaya', 'code'], name='sync_core_c_wilaya_5e81c4_idx'),
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['name_ar'], name='sync_core_c_name_ar_71abf7_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['office', 'unit_code'], name='sync_core_o_office__82e0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['office', 'parent', 'order'], name='sync_core_o_office__2bb019_idx'),
        ),
    ]
