# Generated by Django 5.2.14 on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_core', '0006_official_office_structure'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commune',
            new_name='sync_core_c_wilaya__b0efdd_idx',
            old_name='sync_core_c_wilaya_5e81c4_idx',
        ),
        migrations.RenameIndex(
            model_name='commune',
            new_name='sync_core_c_name_ar_19a13a_idx',
            old_name='sync_core_c_name_ar_71abf7_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationunit',
            new_name='sync_core_o_office__6eb935_idx',
            old_name='sync_core_o_office__82e0e5_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationunit',
            new_name='sync_core_o_office__773d55_idx',
            old_name='sync_core_o_office__2bb019_idx',
        ),
        migrations.AlterField(
            model_name='centraloffice',
            name='office_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم المكتب التقني'),
        ),
    ]
