# Generated by Django 5.2.10 on 2026-01-30 22:38

from django.db import migrations, models  # استيراد عناصر محددة من مكتبة/وحدة


class Migration(migrations.Migration):  # تعريف كلاس (Class)

    initial = True  # تعيين قيمة لمتغير/إعداد

    dependencies = [  # تعيين قيمة لمتغير/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد

    operations = [  # تعيين قيمة لمتغير/إعداد
        migrations.CreateModel(  # سطر كود لتنفيذ منطق/إعداد
            name='تمهين',  # تعيين قيمة لمتغير/إعداد
            fields=[  # تعيين قيمة لمتغير/إعداد
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # تعريف حقل/علاقة في نموذج Django
                ('الرقم_التعريفي', models.CharField(max_length=50, unique=True, verbose_name='الرقم التعريفي')),  # تعريف حقل/علاقة في نموذج Django
                ('اللقب', models.CharField(max_length=100, verbose_name='اللقب')),  # تعريف حقل/علاقة في نموذج Django
                ('الاسم', models.CharField(max_length=100, verbose_name='الاسم')),  # تعريف حقل/علاقة في نموذج Django
                ('الاسم_بالأجنبية', models.CharField(blank=True, max_length=200, null=True, verbose_name='الإسم الكامل باللغة الأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_الميلاد', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),  # تعريف حقل/علاقة في نموذج Django
                ('البلدية', models.CharField(blank=True, max_length=120, null=True, verbose_name='البلدية')),  # تعريف حقل/علاقة في نموذج Django
                ('الولاية', models.CharField(blank=True, max_length=120, null=True, verbose_name='الولاية')),  # تعريف حقل/علاقة في نموذج Django
                ('التخصص', models.CharField(blank=True, max_length=200, null=True, verbose_name='التخصص')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_التسجيل', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التسجيل')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_بداية_التكوين', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية التكوين')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_نهاية_التكوين', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية التكوين')),  # تعريف حقل/علاقة في نموذج Django
                ('السداسي', models.CharField(blank=True, max_length=50, null=True, verbose_name='السداسي')),  # تعريف حقل/علاقة في نموذج Django
                ('الجنس', models.CharField(blank=True, max_length=10, null=True, verbose_name='الجنس')),  # تعريف حقل/علاقة في نموذج Django
                ('الحالة', models.CharField(blank=True, max_length=120, null=True, verbose_name='الحالة')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_الشطب', models.DateField(blank=True, null=True, verbose_name='تاريخ الشطب')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_الشطب', models.CharField(blank=True, max_length=80, null=True, verbose_name='رقم/م-الشطب')),  # تعريف حقل/علاقة في نموذج Django
                ('رمز_التخصص', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز التخصص')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_عقد_الميلاد', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عقد الميلاد')),  # تعريف حقل/علاقة في نموذج Django
                ('زمرة_الدم', models.CharField(blank=True, max_length=10, null=True, verbose_name='زمرة الدم')),  # تعريف حقل/علاقة في نموذج Django
                ('اسم_الأب', models.CharField(blank=True, max_length=120, null=True, verbose_name='إسم الأب')),  # تعريف حقل/علاقة في نموذج Django
                ('لقب_الأم', models.CharField(blank=True, max_length=120, null=True, verbose_name='لقب الأم')),  # تعريف حقل/علاقة في نموذج Django
                ('اسم_الأم', models.CharField(blank=True, max_length=120, null=True, verbose_name='إسم الأم')),  # تعريف حقل/علاقة في نموذج Django
                ('اسم_الأب_بالأجنبية', models.CharField(blank=True, max_length=200, null=True, verbose_name='إسم الأب بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('لقب_الأم_بالأجنبية', models.CharField(blank=True, max_length=200, null=True, verbose_name='لقب الأم بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('اسم_الأم_بالأجنبية', models.CharField(blank=True, max_length=200, null=True, verbose_name='إسم الأم بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية1', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية1')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم1', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم1')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة1', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة1')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية2', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية2')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم2', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم2')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة2', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة2')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية3', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية3')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم3', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم3')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة3', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة3')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية4', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية4')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم4', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم4')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة4', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة4')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية5', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية5')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم5', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم5')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة5', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة5')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية6', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية6')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم6', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم6')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة6', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة6')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية7', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية7')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم7', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم7')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة7', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة7')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية8', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية8')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم8', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم8')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة8', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة8')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية9', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية9')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم9', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم9')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة9', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة9')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية10', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية10')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم10', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم10')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة10', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة10')),  # تعريف حقل/علاقة في نموذج Django
                ('الصورة', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='الصورة')),  # تعريف حقل/علاقة في نموذج Django
                ('البريد_الإلكتروني', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_الهاتف', models.CharField(max_length=30, unique=True, verbose_name='رقم الهاتف')),  # تعريف حقل/علاقة في نموذج Django
                ('النظام', models.CharField(blank=True, max_length=120, null=True, verbose_name='النظام')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_التعريف_الوطني', models.CharField(blank=True, max_length=50, null=True, verbose_name='ب-التعريف الوطنية')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_الضمان_الاجتماعي', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الضمان الاجتماعي')),  # تعريف حقل/علاقة في نموذج Django
                ('العنوان_بالعربية', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان بالعربية')),  # تعريف حقل/علاقة في نموذج Django
                ('ولاية_الإقامة_بالعربية', models.CharField(blank=True, max_length=120, null=True, verbose_name='ولاية الإقامة بالعربية')),  # تعريف حقل/علاقة في نموذج Django
                ('العنوان_بالأجنبية', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('ولاية_الإقامة_بالأجنبية', models.CharField(blank=True, max_length=120, null=True, verbose_name='ولاية الإقامة بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_الإضافة', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),  # تعريف حقل/علاقة في نموذج Django
                ('معيد', models.BooleanField(default=False, verbose_name='معيد')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_التكوين_السابق_للمعيدين', models.DateField(blank=True, null=True, verbose_name='تاريخ التكوين السابق للمعيدين')),  # تعريف حقل/علاقة في نموذج Django
                ('المستخدم', models.CharField(blank=True, max_length=120, null=True, verbose_name='المستخدم')),  # تعريف حقل/علاقة في نموذج Django
            ],  # سطر كود لتنفيذ منطق/إعداد
            options={  # تعيين قيمة لمتغير/إعداد
                'verbose_name': 'متكوّن (عن طريق التمهين)',  # سطر كود لتنفيذ منطق/إعداد
                'verbose_name_plural': 'عن طريق التمهين',  # سطر كود لتنفيذ منطق/إعداد
            },  # سطر كود لتنفيذ منطق/إعداد
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.CreateModel(  # سطر كود لتنفيذ منطق/إعداد
            name='حضوري_أولي',  # تعيين قيمة لمتغير/إعداد
            fields=[  # تعيين قيمة لمتغير/إعداد
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # تعريف حقل/علاقة في نموذج Django
                ('الرقم_التعريفي', models.CharField(max_length=50, unique=True, verbose_name='الرقم التعريفي')),  # تعريف حقل/علاقة في نموذج Django
                ('اللقب', models.CharField(max_length=100, verbose_name='اللقب')),  # تعريف حقل/علاقة في نموذج Django
                ('الاسم', models.CharField(max_length=100, verbose_name='الاسم')),  # تعريف حقل/علاقة في نموذج Django
                ('الاسم_بالأجنبية', models.CharField(blank=True, max_length=200, null=True, verbose_name='الإسم الكامل باللغة الأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_الميلاد', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),  # تعريف حقل/علاقة في نموذج Django
                ('البلدية', models.CharField(blank=True, max_length=120, null=True, verbose_name='البلدية')),  # تعريف حقل/علاقة في نموذج Django
                ('الولاية', models.CharField(blank=True, max_length=120, null=True, verbose_name='الولاية')),  # تعريف حقل/علاقة في نموذج Django
                ('التخصص', models.CharField(blank=True, max_length=200, null=True, verbose_name='التخصص')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_التسجيل', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التسجيل')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_بداية_التكوين', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية التكوين')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_نهاية_التكوين', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية التكوين')),  # تعريف حقل/علاقة في نموذج Django
                ('السداسي', models.CharField(blank=True, max_length=50, null=True, verbose_name='السداسي')),  # تعريف حقل/علاقة في نموذج Django
                ('الجنس', models.CharField(blank=True, max_length=10, null=True, verbose_name='الجنس')),  # تعريف حقل/علاقة في نموذج Django
                ('الحالة', models.CharField(blank=True, max_length=120, null=True, verbose_name='الحالة')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_الشطب', models.DateField(blank=True, null=True, verbose_name='تاريخ الشطب')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_الشطب', models.CharField(blank=True, max_length=80, null=True, verbose_name='رقم/م-الشطب')),  # تعريف حقل/علاقة في نموذج Django
                ('رمز_التخصص', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز التخصص')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_عقد_الميلاد', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عقد الميلاد')),  # تعريف حقل/علاقة في نموذج Django
                ('زمرة_الدم', models.CharField(blank=True, max_length=10, null=True, verbose_name='زمرة الدم')),  # تعريف حقل/علاقة في نموذج Django
                ('اسم_الأب', models.CharField(blank=True, max_length=120, null=True, verbose_name='إسم الأب')),  # تعريف حقل/علاقة في نموذج Django
                ('لقب_الأم', models.CharField(blank=True, max_length=120, null=True, verbose_name='لقب الأم')),  # تعريف حقل/علاقة في نموذج Django
                ('اسم_الأم', models.CharField(blank=True, max_length=120, null=True, verbose_name='إسم الأم')),  # تعريف حقل/علاقة في نموذج Django
                ('اسم_الأب_بالأجنبية', models.CharField(blank=True, max_length=200, null=True, verbose_name='إسم الأب بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('لقب_الأم_بالأجنبية', models.CharField(blank=True, max_length=200, null=True, verbose_name='لقب الأم بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('اسم_الأم_بالأجنبية', models.CharField(blank=True, max_length=200, null=True, verbose_name='إسم الأم بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية1', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية1')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم1', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم1')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة1', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة1')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية2', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية2')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم2', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم2')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة2', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة2')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية3', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية3')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم3', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم3')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة3', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة3')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية4', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية4')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم4', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم4')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة4', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة4')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية5', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية5')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم5', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم5')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة5', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة5')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية6', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية6')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم6', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم6')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة6', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة6')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية7', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية7')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم7', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم7')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة7', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة7')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية8', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية8')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم8', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم8')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة8', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة8')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية9', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية9')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم9', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم9')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة9', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة9')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية10', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية10')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم10', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم10')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة10', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة10')),  # تعريف حقل/علاقة في نموذج Django
                ('الصورة', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='الصورة')),  # تعريف حقل/علاقة في نموذج Django
                ('البريد_الإلكتروني', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_الهاتف', models.CharField(max_length=30, unique=True, verbose_name='رقم الهاتف')),  # تعريف حقل/علاقة في نموذج Django
                ('النظام', models.CharField(blank=True, max_length=120, null=True, verbose_name='النظام')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_التعريف_الوطني', models.CharField(blank=True, max_length=50, null=True, verbose_name='ب-التعريف الوطنية')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_الضمان_الاجتماعي', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الضمان الاجتماعي')),  # تعريف حقل/علاقة في نموذج Django
                ('العنوان_بالعربية', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان بالعربية')),  # تعريف حقل/علاقة في نموذج Django
                ('ولاية_الإقامة_بالعربية', models.CharField(blank=True, max_length=120, null=True, verbose_name='ولاية الإقامة بالعربية')),  # تعريف حقل/علاقة في نموذج Django
                ('العنوان_بالأجنبية', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('ولاية_الإقامة_بالأجنبية', models.CharField(blank=True, max_length=120, null=True, verbose_name='ولاية الإقامة بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_الإضافة', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),  # تعريف حقل/علاقة في نموذج Django
            ],  # سطر كود لتنفيذ منطق/إعداد
            options={  # تعيين قيمة لمتغير/إعداد
                'verbose_name': 'متكوّن (حضوري أولي)',  # سطر كود لتنفيذ منطق/إعداد
                'verbose_name_plural': 'حضوري أولي',  # سطر كود لتنفيذ منطق/إعداد
            },  # سطر كود لتنفيذ منطق/إعداد
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.CreateModel(  # سطر كود لتنفيذ منطق/إعداد
            name='مسائي_ومعابر',  # تعيين قيمة لمتغير/إعداد
            fields=[  # تعيين قيمة لمتغير/إعداد
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # تعريف حقل/علاقة في نموذج Django
                ('الرقم_التعريفي', models.CharField(max_length=50, unique=True, verbose_name='الرقم التعريفي')),  # تعريف حقل/علاقة في نموذج Django
                ('اللقب', models.CharField(max_length=100, verbose_name='اللقب')),  # تعريف حقل/علاقة في نموذج Django
                ('الاسم', models.CharField(max_length=100, verbose_name='الاسم')),  # تعريف حقل/علاقة في نموذج Django
                ('الاسم_بالأجنبية', models.CharField(blank=True, max_length=200, null=True, verbose_name='الإسم الكامل باللغة الأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_الميلاد', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),  # تعريف حقل/علاقة في نموذج Django
                ('البلدية', models.CharField(blank=True, max_length=120, null=True, verbose_name='البلدية')),  # تعريف حقل/علاقة في نموذج Django
                ('الولاية', models.CharField(blank=True, max_length=120, null=True, verbose_name='الولاية')),  # تعريف حقل/علاقة في نموذج Django
                ('التخصص', models.CharField(blank=True, max_length=200, null=True, verbose_name='التخصص')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_التسجيل', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التسجيل')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_بداية_التكوين', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية التكوين')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_نهاية_التكوين', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية التكوين')),  # تعريف حقل/علاقة في نموذج Django
                ('السداسي', models.CharField(blank=True, max_length=50, null=True, verbose_name='السداسي')),  # تعريف حقل/علاقة في نموذج Django
                ('الجنس', models.CharField(blank=True, max_length=10, null=True, verbose_name='الجنس')),  # تعريف حقل/علاقة في نموذج Django
                ('الحالة', models.CharField(blank=True, max_length=120, null=True, verbose_name='الحالة')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_الشطب', models.DateField(blank=True, null=True, verbose_name='تاريخ الشطب')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_الشطب', models.CharField(blank=True, max_length=80, null=True, verbose_name='رقم/م-الشطب')),  # تعريف حقل/علاقة في نموذج Django
                ('رمز_التخصص', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز التخصص')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_عقد_الميلاد', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عقد الميلاد')),  # تعريف حقل/علاقة في نموذج Django
                ('زمرة_الدم', models.CharField(blank=True, max_length=10, null=True, verbose_name='زمرة الدم')),  # تعريف حقل/علاقة في نموذج Django
                ('اسم_الأب', models.CharField(blank=True, max_length=120, null=True, verbose_name='إسم الأب')),  # تعريف حقل/علاقة في نموذج Django
                ('لقب_الأم', models.CharField(blank=True, max_length=120, null=True, verbose_name='لقب الأم')),  # تعريف حقل/علاقة في نموذج Django
                ('اسم_الأم', models.CharField(blank=True, max_length=120, null=True, verbose_name='إسم الأم')),  # تعريف حقل/علاقة في نموذج Django
                ('اسم_الأب_بالأجنبية', models.CharField(blank=True, max_length=200, null=True, verbose_name='إسم الأب بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('لقب_الأم_بالأجنبية', models.CharField(blank=True, max_length=200, null=True, verbose_name='لقب الأم بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('اسم_الأم_بالأجنبية', models.CharField(blank=True, max_length=200, null=True, verbose_name='إسم الأم بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية1', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية1')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم1', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم1')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة1', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة1')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية2', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية2')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم2', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم2')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة2', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة2')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية3', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية3')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم3', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم3')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة3', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة3')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية4', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية4')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم4', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم4')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة4', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة4')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية5', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية5')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم5', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم5')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة5', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة5')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية6', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية6')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم6', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم6')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة6', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة6')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية7', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية7')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم7', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم7')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة7', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة7')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية8', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية8')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم8', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم8')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة8', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة8')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية9', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية9')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم9', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم9')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة9', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة9')),  # تعريف حقل/علاقة في نموذج Django
                ('اللجنة_التأديبية10', models.CharField(blank=True, max_length=200, null=True, verbose_name='اللجنة التأديبية10')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم10', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم10')),  # تعريف حقل/علاقة في نموذج Django
                ('العقوبة10', models.CharField(blank=True, max_length=200, null=True, verbose_name='العقوبة10')),  # تعريف حقل/علاقة في نموذج Django
                ('الصورة', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='الصورة')),  # تعريف حقل/علاقة في نموذج Django
                ('البريد_الإلكتروني', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_الهاتف', models.CharField(max_length=30, unique=True, verbose_name='رقم الهاتف')),  # تعريف حقل/علاقة في نموذج Django
                ('النظام', models.CharField(blank=True, max_length=120, null=True, verbose_name='النظام')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_التعريف_الوطني', models.CharField(blank=True, max_length=50, null=True, verbose_name='ب-التعريف الوطنية')),  # تعريف حقل/علاقة في نموذج Django
                ('رقم_الضمان_الاجتماعي', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الضمان الاجتماعي')),  # تعريف حقل/علاقة في نموذج Django
                ('العنوان_بالعربية', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان بالعربية')),  # تعريف حقل/علاقة في نموذج Django
                ('ولاية_الإقامة_بالعربية', models.CharField(blank=True, max_length=120, null=True, verbose_name='ولاية الإقامة بالعربية')),  # تعريف حقل/علاقة في نموذج Django
                ('العنوان_بالأجنبية', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('ولاية_الإقامة_بالأجنبية', models.CharField(blank=True, max_length=120, null=True, verbose_name='ولاية الإقامة بالأجنبية')),  # تعريف حقل/علاقة في نموذج Django
                ('تاريخ_الإضافة', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),  # تعريف حقل/علاقة في نموذج Django
            ],  # سطر كود لتنفيذ منطق/إعداد
            options={  # تعيين قيمة لمتغير/إعداد
                'verbose_name': 'متكوّن (الدروس المسائية والمعابر)',  # سطر كود لتنفيذ منطق/إعداد
                'verbose_name_plural': 'الدروس المسائية والمعابر',  # سطر كود لتنفيذ منطق/إعداد
            },  # سطر كود لتنفيذ منطق/إعداد
        ),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد
