# Generated by ChatGPT on 2026-02-02

from django.db import migrations, models  # استيراد عناصر محددة من مكتبة/وحدة


class Migration(migrations.Migration):  # تعريف كلاس (Class)

    dependencies = [  # تعيين قيمة لمتغير/إعداد
        ('trainees', '0003_remove_disciplinary_and_photo'),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد

    operations = [  # تعيين قيمة لمتغير/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='تمهين',  # تعيين قيمة لمتغير/إعداد
            name='الرقم_التعريفي',  # تعيين قيمة لمتغير/إعداد
            field=models.CharField(db_index=True, max_length=50, null=True, blank=True, verbose_name='الرقم التعريفي'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='تمهين',  # تعيين قيمة لمتغير/إعداد
            name='رقم_الهاتف',  # تعيين قيمة لمتغير/إعداد
            field=models.CharField(db_index=True, max_length=30, null=True, blank=True, verbose_name='رقم الهاتف'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='حضوري_أولي',  # تعيين قيمة لمتغير/إعداد
            name='الرقم_التعريفي',  # تعيين قيمة لمتغير/إعداد
            field=models.CharField(db_index=True, max_length=50, null=True, blank=True, verbose_name='الرقم التعريفي'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='حضوري_أولي',  # تعيين قيمة لمتغير/إعداد
            name='رقم_الهاتف',  # تعيين قيمة لمتغير/إعداد
            field=models.CharField(db_index=True, max_length=30, null=True, blank=True, verbose_name='رقم الهاتف'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='مسائي_ومعابر',  # تعيين قيمة لمتغير/إعداد
            name='الرقم_التعريفي',  # تعيين قيمة لمتغير/إعداد
            field=models.CharField(db_index=True, max_length=50, null=True, blank=True, verbose_name='الرقم التعريفي'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='مسائي_ومعابر',  # تعيين قيمة لمتغير/إعداد
            name='رقم_الهاتف',  # تعيين قيمة لمتغير/إعداد
            field=models.CharField(db_index=True, max_length=30, null=True, blank=True, verbose_name='رقم الهاتف'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد
