# Generated by Django 5.2.10 on 2026-02-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0004_make_id_and_phone_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='تمهين',
            name='مفترض',
            field=models.BooleanField(default=False, verbose_name='مفترض'),
        ),
        migrations.AddField(
            model_name='حضوري_أولي',
            name='مفترض',
            field=models.BooleanField(default=False, verbose_name='مفترض'),
        ),
        migrations.AddField(
            model_name='مسائي_ومعابر',
            name='مفترض',
            field=models.BooleanField(default=False, verbose_name='مفترض'),
        ),
    ]
