# Generated by ChatGPT on 2026-02-10

from __future__ import annotations  # استيراد عناصر محددة من مكتبة/وحدة

from django.db import migrations  # استيراد عناصر محددة من مكتبة/وحدة


def forwards(apps, schema_editor):  # تعريف دالة (Function)
    from trainees.semester_utils import compute_semester_with_repeater, normalize_repeater_training_dates  # استيراد عناصر محددة من مكتبة/وحدة

    for model_name in ("حضوري_أولي", "تمهين", "مسائي_ومعابر"):  # حلقة تكرار (For)
        Model = apps.get_model("trainees", model_name)  # تعيين قيمة لمتغير/إعداد
        fields = ["id", "تاريخ_بداية_التكوين", "تاريخ_نهاية_التكوين", "السداسي"]  # تعيين قيمة لمتغير/إعداد
        if model_name == "تمهين":  # شرط (If)
            fields += ["معيد", "تاريخ_التكوين_السابق_للمعيدين"]  # تعيين قيمة لمتغير/إعداد
        qs = Model.objects.all().only(*fields)  # تعيين قيمة لمتغير/إعداد

        to_update = []  # تعيين قيمة لمتغير/إعداد
        if model_name == "تمهين":  # شرط (If)
            update_fields = ["تاريخ_نهاية_التكوين", "تاريخ_التكوين_السابق_للمعيدين", "السداسي"]  # تعيين قيمة لمتغير/إعداد
        else:  # فرع بديل (Else)
            update_fields = ["السداسي"]  # تعيين قيمة لمتغير/إعداد

        for obj in qs.iterator(chunk_size=2000):  # حلقة تكرار (For)
            changed_dates = normalize_repeater_training_dates(obj)  # تعيين قيمة لمتغير/إعداد
            is_repeater = bool(getattr(obj, "معيد", False))  # تعيين قيمة لمتغير/إعداد
            sem = compute_semester_with_repeater(  # تعيين قيمة لمتغير/إعداد
                obj.تاريخ_بداية_التكوين,  # سطر كود لتنفيذ منطق/إعداد
                obj.تاريخ_نهاية_التكوين,  # سطر كود لتنفيذ منطق/إعداد
                is_repeater=is_repeater,  # تعيين قيمة لمتغير/إعداد
            )  # سطر كود لتنفيذ منطق/إعداد
            if not sem:  # شرط (If)
                continue  # سطر كود لتنفيذ منطق/إعداد

            changed_sem = sem != (obj.السداسي or "")  # تعيين قيمة لمتغير/إعداد
            if changed_sem:  # شرط (If)
                obj.السداسي = sem  # تعيين قيمة لمتغير/إعداد
            if changed_sem or changed_dates:  # شرط (If)
                to_update.append(obj)  # سطر كود لتنفيذ منطق/إعداد

        if to_update:  # شرط (If)
            Model.objects.bulk_update(to_update, update_fields, batch_size=1000)  # تعيين قيمة لمتغير/إعداد


def backwards(apps, schema_editor):  # تعريف دالة (Function)
    pass  # سطر كود لتنفيذ منطق/إعداد


class Migration(migrations.Migration):  # تعريف كلاس (Class)

    dependencies = [  # تعيين قيمة لمتغير/إعداد
        ("trainees", "0008_recompute_semester"),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد

    operations = [  # تعيين قيمة لمتغير/إعداد
        migrations.RunPython(forwards, backwards),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد
