# Generated by Django 5.2.10 on 2026-02-11 13:50

from django.db import migrations, models  # استيراد عناصر محددة من مكتبة/وحدة


class Migration(migrations.Migration):  # تعريف كلاس (Class)

    dependencies = [  # تعيين قيمة لمتغير/إعداد
        ('trainees', '0011_customfield_key_autogen'),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد

    operations = [  # تعيين قيمة لمتغير/إعداد
        migrations.AlterModelOptions(  # سطر كود لتنفيذ منطق/إعداد
            name='customfield',  # تعيين قيمة لمتغير/إعداد
            options={},  # تعيين قيمة لمتغير/إعداد
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.RenameIndex(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfieldvalue',  # تعيين قيمة لمتغير/إعداد
            new_name='trainees_cu_content_e07ebe_idx',  # تعيين قيمة لمتغير/إعداد
            old_name='trainees_cus_content_7a6c1e_idx',  # تعيين قيمة لمتغير/إعداد
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.RenameIndex(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfieldvalue',  # تعيين قيمة لمتغير/إعداد
            new_name='trainees_cu_field_i_d6f192_idx',  # تعيين قيمة لمتغير/إعداد
            old_name='trainees_cus_field_2e9a6e_idx',  # تعيين قيمة لمتغير/إعداد
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.RemoveField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfield',  # تعيين قيمة لمتغير/إعداد
            name='choices',  # تعيين قيمة لمتغير/إعداد
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfield',  # تعيين قيمة لمتغير/إعداد
            name='field_type',  # تعيين قيمة لمتغير/إعداد
            field=models.CharField(max_length=30, verbose_name='نوع الحقل'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfield',  # تعيين قيمة لمتغير/إعداد
            name='key',  # تعيين قيمة لمتغير/إعداد
            field=models.SlugField(blank=True, editable=False, max_length=80, unique=True, verbose_name='المفتاح (فريد)'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfield',  # تعيين قيمة لمتغير/إعداد
            name='label',  # تعيين قيمة لمتغير/إعداد
            field=models.CharField(max_length=150, verbose_name='اسم العمود'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfield',  # تعيين قيمة لمتغير/إعداد
            name='order',  # تعيين قيمة لمتغير/إعداد
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد
