# Generated by Django 5.2.10 on 2026-02-11 14:25

from django.db import migrations, models  # استيراد عناصر محددة من مكتبة/وحدة


class Migration(migrations.Migration):  # تعريف كلاس (Class)

    dependencies = [  # تعيين قيمة لمتغير/إعداد
        ('trainees', '0012_alter_customfield_options_and_more'),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد

    operations = [  # تعيين قيمة لمتغير/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfield',  # تعيين قيمة لمتغير/إعداد
            name='field_type',  # تعيين قيمة لمتغير/إعداد
            field=models.CharField(choices=[('text', 'نص'), ('date', 'تاريخ'), ('number', 'رقم'), ('boolean', 'نعم / لا')], default='text', max_length=20, verbose_name='نوع الحقل'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد
