# Generated by ChatGPT on 2026-02-11

from django.db import migrations, models  # استيراد عناصر محددة من مكتبة/وحدة


class Migration(migrations.Migration):  # تعريف كلاس (Class)

    dependencies = [  # تعيين قيمة لمتغير/إعداد
        ('trainees', '0013_alter_customfield_field_type'),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد

    operations = [  # تعيين قيمة لمتغير/إعداد
        migrations.AddField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfield',  # تعيين قيمة لمتغير/إعداد
            name='program',  # تعيين قيمة لمتغير/إعداد
            field=models.CharField(choices=[('all', 'كل الأنماط'), ('initial', 'حضوري أولي'), ('apprentice', 'تمهين'), ('evening', 'مسائي ومعابر')], default='all', max_length=20, verbose_name='النمط'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد
