# Generated by Django 5.2.10 on 2026-02-11 19:45

from django.db import migrations  # استيراد عناصر محددة من مكتبة/وحدة


class Migration(migrations.Migration):  # تعريف كلاس (Class)

    dependencies = [  # تعيين قيمة لمتغير/إعداد
        ('trainees', '0012_customfield_program_and_order'),  # سطر كود لتنفيذ منطق/إعداد
        ('trainees', '0014_add_customfield_program'),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد

    operations = [  # تعيين قيمة لمتغير/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد
