# Generated by Django 5.2.11 on 2026-02-15 13:41

from django.db import migrations, models  # استيراد عناصر محددة من مكتبة/وحدة


class Migration(migrations.Migration):  # تعريف كلاس (Class)

    dependencies = [  # تعيين قيمة لمتغير/إعداد
        ('contenttypes', '0002_remove_content_type_name'),  # سطر كود لتنفيذ منطق/إعداد
        ('trainees', '0015_merge_20260211_2045'),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد

    operations = [  # تعيين قيمة لمتغير/إعداد
        migrations.AlterModelOptions(  # سطر كود لتنفيذ منطق/إعداد
            name='customfield',  # تعيين قيمة لمتغير/إعداد
            options={},  # تعيين قيمة لمتغير/إعداد
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.RemoveIndex(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfieldvalue',  # تعيين قيمة لمتغير/إعداد
            name='trainees_cu_field_i_d6f192_idx',  # تعيين قيمة لمتغير/إعداد
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfield',  # تعيين قيمة لمتغير/إعداد
            name='field_type',  # تعيين قيمة لمتغير/إعداد
            field=models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('date', 'تاريخ'), ('boolean', 'نعم / لا')], default='text', max_length=20, verbose_name='نوع الحقل'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfield',  # تعيين قيمة لمتغير/إعداد
            name='key',  # تعيين قيمة لمتغير/إعداد
            field=models.SlugField(blank=True, editable=False, help_text='اسم داخلي فريد (بدون مسافات). مثال: رقم_ملف', max_length=80, unique=True, verbose_name='المفتاح (فريد)'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AlterField(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfield',  # تعيين قيمة لمتغير/إعداد
            name='program',  # تعيين قيمة لمتغير/إعداد
            field=models.CharField(choices=[('all', 'كل الأنماط'), ('initial', 'حضوري أولي'), ('apprentice', 'تمهين'), ('evening', 'مسائي ومعابر')], default='all', max_length=20, verbose_name='النمط'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
        migrations.AddIndex(  # سطر كود لتنفيذ منطق/إعداد
            model_name='customfieldvalue',  # تعيين قيمة لمتغير/إعداد
            index=models.Index(fields=['field', 'content_type', 'object_id'], name='trainees_cu_field_i_7c5c2b_idx'),  # تعريف حقل/علاقة في نموذج Django
        ),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد
