# Generated by ChatGPT on 2026-02-15

from django.db import migrations, models  # استيراد عناصر محددة من مكتبة/وحدة
import django.db.models.deletion  # استيراد مكتبة/وحدة بايثون


class Migration(migrations.Migration):  # تعريف كلاس (Class)

    dependencies = [  # تعيين قيمة لمتغير/إعداد
        ("contenttypes", "0002_remove_content_type_name"),  # سطر كود لتنفيذ منطق/إعداد
        ("trainees", "0015_merge_20260211_2045"),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد

    operations = [  # تعيين قيمة لمتغير/إعداد
        migrations.CreateModel(  # سطر كود لتنفيذ منطق/إعداد
            name="Attendance",  # تعيين قيمة لمتغير/إعداد
            fields=[  # تعيين قيمة لمتغير/إعداد
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),  # تعريف حقل/علاقة في نموذج Django
                ("object_id", models.PositiveIntegerField()),  # تعريف حقل/علاقة في نموذج Django
                ("date", models.DateField(verbose_name="التاريخ")),  # تعريف حقل/علاقة في نموذج Django
                (  # سطر كود لتنفيذ منطق/إعداد
                    "status",  # سطر كود لتنفيذ منطق/إعداد
                    models.CharField(  # تعريف حقل/علاقة في نموذج Django
                        choices=[  # تعيين قيمة لمتغير/إعداد
                            ("present", "حاضر"),  # سطر كود لتنفيذ منطق/إعداد
                            ("absent_excused", "غائب بعذر"),  # سطر كود لتنفيذ منطق/إعداد
                            ("absent_unexcused", "غائب بدون عذر"),  # سطر كود لتنفيذ منطق/إعداد
                        ],  # سطر كود لتنفيذ منطق/إعداد
                        default="present",  # تعيين قيمة لمتغير/إعداد
                        max_length=20,  # تعيين قيمة لمتغير/إعداد
                        verbose_name="الحالة",  # تعيين قيمة لمتغير/إعداد
                    ),  # سطر كود لتنفيذ منطق/إعداد
                ),  # سطر كود لتنفيذ منطق/إعداد
                ("note", models.CharField(blank=True, max_length=255, verbose_name="ملاحظة")),  # تعريف حقل/علاقة في نموذج Django
                (  # سطر كود لتنفيذ منطق/إعداد
                    "recorded_by_username",  # سطر كود لتنفيذ منطق/إعداد
                    models.CharField(  # تعريف حقل/علاقة في نموذج Django
                        blank=True,  # تعيين قيمة لمتغير/إعداد
                        help_text="اسم المستخدم الذي سجّل الحضور (اختياري)",  # تعيين قيمة لمتغير/إعداد
                        max_length=150,  # تعيين قيمة لمتغير/إعداد
                        verbose_name="المسجل",  # تعيين قيمة لمتغير/إعداد
                    ),  # سطر كود لتنفيذ منطق/إعداد
                ),  # سطر كود لتنفيذ منطق/إعداد
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإضافة")),  # تعريف حقل/علاقة في نموذج Django
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث")),  # تعريف حقل/علاقة في نموذج Django
                (  # سطر كود لتنفيذ منطق/إعداد
                    "content_type",  # سطر كود لتنفيذ منطق/إعداد
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),  # تعريف حقل/علاقة في نموذج Django
                ),  # سطر كود لتنفيذ منطق/إعداد
            ],  # سطر كود لتنفيذ منطق/إعداد
            options={  # تعيين قيمة لمتغير/إعداد
                "verbose_name": "حضور",  # سطر كود لتنفيذ منطق/إعداد
                "verbose_name_plural": "الحضور",  # سطر كود لتنفيذ منطق/إعداد
                "ordering": ["-date", "-created_at"],  # سطر كود لتنفيذ منطق/إعداد
                "unique_together": {("content_type", "object_id", "date")},  # سطر كود لتنفيذ منطق/إعداد
                "indexes": [  # سطر كود لتنفيذ منطق/إعداد
                    models.Index(fields=["content_type", "object_id", "date"], name="trainees_at_content_2f62f1_idx"),  # تعريف حقل/علاقة في نموذج Django
                    models.Index(fields=["date", "status"], name="trainees_at_date_2c6d1c_idx"),  # تعريف حقل/علاقة في نموذج Django
                ],  # سطر كود لتنفيذ منطق/إعداد
            },  # سطر كود لتنفيذ منطق/إعداد
        ),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد
