# Generated by Django 5.2.11 on 2026-02-15 14:25

from django.db import migrations  # استيراد عناصر محددة من مكتبة/وحدة


class Migration(migrations.Migration):  # تعريف كلاس (Class)

    dependencies = [  # تعيين قيمة لمتغير/إعداد
        ('trainees', '0016_alter_customfield_options_and_more'),  # سطر كود لتنفيذ منطق/إعداد
        ('trainees', '0016_attendance'),  # سطر كود لتنفيذ منطق/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد

    operations = [  # تعيين قيمة لمتغير/إعداد
    ]  # سطر كود لتنفيذ منطق/إعداد
