# Generated by Django 5.2.11 on 2026-02-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0005_تمهين_مفترض_حضوري_أولي_مفترض_مسائي_ومعابر_مفترض'),
        ('trainees', '0007_remove_تمهين_الحالة_الموحدة_and_more'),
        ('trainees', '0018_merge_20260216_2041'),
    ]

    operations = [
    ]
