# Generated by Django 5.2.11 on 2026-03-11 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0020_promotion_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='تمهين',
            name='الدفعة',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_trainees', to='trainees.دفعة', verbose_name='الدفعة'),
        ),
        migrations.AlterField(
            model_name='حضوري_أولي',
            name='الدفعة',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_trainees', to='trainees.دفعة', verbose_name='الدفعة'),
        ),
        migrations.AlterField(
            model_name='دفعة',
            name='بداية_السداسي_1',
            field=models.DateField(blank=True, null=True, verbose_name='بداية السداسي 1'),
        ),
        migrations.AlterField(
            model_name='دفعة',
            name='بداية_السداسي_2',
            field=models.DateField(blank=True, null=True, verbose_name='بداية السداسي 2'),
        ),
        migrations.AlterField(
            model_name='دفعة',
            name='بداية_السداسي_3',
            field=models.DateField(blank=True, null=True, verbose_name='بداية السداسي 3'),
        ),
        migrations.AlterField(
            model_name='دفعة',
            name='بداية_السداسي_4',
            field=models.DateField(blank=True, null=True, verbose_name='بداية السداسي 4'),
        ),
        migrations.AlterField(
            model_name='مسائي_ومعابر',
            name='الدفعة',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_trainees', to='trainees.دفعة', verbose_name='الدفعة'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
