# Generated by Django 5.2.11 on 2026-03-13 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0022_recompute_semester_from_promotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='دفعة',
            options={'ordering': ['-السنة', '-رقم_الدورة'], 'verbose_name': 'دفعة', 'verbose_name_plural': 'الدفعات'},
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'دخول'), ('logout', 'خروج'), ('view', 'عرض'), ('add', 'إضافة'), ('change', 'تعديل'), ('delete', 'حذف'), ('export', 'تصدير'), ('access_denied', 'منع وصول')], max_length=20, verbose_name='الإجراء')),
                ('program', models.CharField(blank=True, max_length=20, null=True, verbose_name='البرنامج')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='السجل')),
                ('details', models.TextField(blank=True, default='', verbose_name='تفاصيل')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='المسار')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل النشاط',
                'verbose_name_plural': 'سجل النشاط',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_admin_panel', models.BooleanField(default=False, verbose_name='يدخل لوحة الإدارة')),
                ('can_manage_all_programs', models.BooleanField(default=False, verbose_name='نائب المدير: يدير كل الأنماط')),
                ('initial_view', models.BooleanField(default=False, verbose_name='الحضوري: عرض')),
                ('initial_add', models.BooleanField(default=False, verbose_name='الحضوري: إضافة')),
                ('initial_change', models.BooleanField(default=False, verbose_name='الحضوري: تعديل')),
                ('initial_delete', models.BooleanField(default=False, verbose_name='الحضوري: حذف')),
                ('apprentice_view', models.BooleanField(default=False, verbose_name='التمهين: عرض')),
                ('apprentice_add', models.BooleanField(default=False, verbose_name='التمهين: إضافة')),
                ('apprentice_change', models.BooleanField(default=False, verbose_name='التمهين: تعديل')),
                ('apprentice_delete', models.BooleanField(default=False, verbose_name='التمهين: حذف')),
                ('evening_view', models.BooleanField(default=False, verbose_name='المسائي: عرض')),
                ('evening_add', models.BooleanField(default=False, verbose_name='المسائي: إضافة')),
                ('evening_change', models.BooleanField(default=False, verbose_name='المسائي: تعديل')),
                ('evening_delete', models.BooleanField(default=False, verbose_name='المسائي: حذف')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='عرض التقارير')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='تصدير البيانات')),
                ('force_password_change', models.BooleanField(default=False, verbose_name='إجبار تغيير كلمة المرور عند أول دخول')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحيات المستخدم',
                'verbose_name_plural': 'صلاحيات المستخدمين',
            },
        ),
    ]
