# Generated by Django 5.2.11 on 2026-03-19 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0023_activitylog'),
        ('trainees', '0023_activitylog_and_labels'),
        ('trainees', '0023_alter_دفعة_options_activitylog_useraccessprofile'),
        ('trainees', '0026_compact_registration_numbers'),
    ]

    operations = [
    ]
