# Generated by Django 5.2.11 on 2026-03-24 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0027_merge_20260319_0214'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='كشفغياب',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('البرنامج', models.CharField(choices=[('initial', 'حضوري أولي'), ('apprentice', 'تمهين'), ('evening', 'مسائي ومعابر')], max_length=20, verbose_name='النمط')),
                ('التخصص', models.CharField(blank=True, default='', max_length=200, verbose_name='التخصص')),
                ('الشهر', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('السنة', models.PositiveIntegerField(verbose_name='السنة')),
                ('يوم_الدراسة_1', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'الإثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], null=True, verbose_name='يوم الدراسة 1')),
                ('يوم_الدراسة_2', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'الإثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], null=True, verbose_name='يوم الدراسة 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_sheets', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('الدفعة', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sheets', to='trainees.دفعة', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'جدول غيابات',
                'verbose_name_plural': 'جداول الغيابات',
                'ordering': ['-السنة', '-الشهر', 'البرنامج', 'التخصص'],
            },
        ),
        migrations.CreateModel(
            name='خليةغياب',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_id', models.PositiveIntegerField(verbose_name='معرّف المتكوّن')),
                ('التاريخ', models.DateField(verbose_name='التاريخ')),
                ('الحالة', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('excused', 'غائب بعذر'), ('late', 'متأخر')], default='present', max_length=20, verbose_name='الحالة')),
                ('ملاحظة', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_entries', to=settings.AUTH_USER_MODEL, verbose_name='سجل بواسطة')),
                ('الكشف', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trainees.كشفغياب', verbose_name='الجدول')),
            ],
            options={
                'verbose_name': 'خلية غياب',
                'verbose_name_plural': 'خلايا الغياب',
                'ordering': ['التاريخ', 'trainee_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='كشفغياب',
            constraint=models.UniqueConstraint(fields=('البرنامج', 'الدفعة', 'التخصص', 'الشهر', 'السنة'), name='trainees_unique_attendance_sheet_per_scope'),
        ),
        migrations.AddIndex(
            model_name='خليةغياب',
            index=models.Index(fields=['الكشف', 'التاريخ'], name='trainees_خل_الكشف_i_df89a2_idx'),
        ),
        migrations.AddIndex(
            model_name='خليةغياب',
            index=models.Index(fields=['الكشف', 'trainee_id'], name='trainees_خل_الكشف_i_266352_idx'),
        ),
        migrations.AddConstraint(
            model_name='خليةغياب',
            constraint=models.UniqueConstraint(fields=('الكشف', 'trainee_id', 'التاريخ'), name='trainees_unique_attendance_cell'),
        ),
    ]
