# Generated by Django 5.2.11 on 2026-03-26 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0029_attendance_periods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='خليةغياب',
            options={'ordering': ['التاريخ', 'trainee_id', 'رقم_الخانة'], 'verbose_name': 'خلية غياب', 'verbose_name_plural': 'خلايا الغياب'},
        ),
        migrations.RemoveConstraint(
            model_name='خليةغياب',
            name='trainees_unique_attendance_cell_period',
        ),
        migrations.RemoveIndex(
            model_name='خليةغياب',
            name='trainees_خل_الكشف_i_df89a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='خليةغياب',
            name='trainees_خل_الكشف_i_266352_idx',
        ),
        migrations.RemoveIndex(
            model_name='خليةغياب',
            name='trainees_att_cell_period_idx',
        ),
        migrations.RemoveField(
            model_name='خليةغياب',
            name='الفترة',
        ),
        migrations.AddField(
            model_name='خليةغياب',
            name='رقم_الخانة',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='رقم الخانة'),
        ),
        migrations.AddIndex(
            model_name='خليةغياب',
            index=models.Index(fields=['الكشف', 'التاريخ', 'رقم_الخانة'], name='trainees_خل_الكشف_i_e2b8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='خليةغياب',
            index=models.Index(fields=['الكشف', 'trainee_id', 'التاريخ', 'رقم_الخانة'], name='trainees_خل_الكشف_i_aaa339_idx'),
        ),
        migrations.AddConstraint(
            model_name='خليةغياب',
            constraint=models.UniqueConstraint(fields=('الكشف', 'trainee_id', 'التاريخ', 'رقم_الخانة'), name='trainees_unique_attendance_cell_slot'),
        ),
    ]
