# Generated by Django 5.2.11 on 2026-03-26 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0030_alter_خليةغياب_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='كشفغياب',
            name='يوم_الدراسة_1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'الأحد'), (1, 'الإثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت')], null=True, verbose_name='يوم الدراسة 1'),
        ),
        migrations.AlterField(
            model_name='كشفغياب',
            name='يوم_الدراسة_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'الأحد'), (1, 'الإثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت')], null=True, verbose_name='يوم الدراسة 2'),
        ),
        migrations.CreateModel(
            name='AttendanceStatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('initial', 'حضوري أولي'), ('apprentice', 'تمهين'), ('evening', 'مسائي ومعابر')], max_length=20, verbose_name='النمط')),
                ('month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('specialty', models.CharField(blank=True, default='', max_length=200, verbose_name='التخصص المطلوب')),
                ('trainee_id', models.PositiveIntegerField(verbose_name='معرّف المتكوّن')),
                ('trainee_name', models.CharField(max_length=255, verbose_name='اسم المتكوّن')),
                ('trainee_specialty', models.CharField(blank=True, default='', max_length=200, verbose_name='تخصص المتكوّن')),
                ('present_count', models.PositiveIntegerField(default=0, verbose_name='عدد الحضور')),
                ('absent_count', models.PositiveIntegerField(default=0, verbose_name='عدد الغيابات')),
                ('excused_count', models.PositiveIntegerField(default=0, verbose_name='عدد الغيابات بعذر')),
                ('late_count', models.PositiveIntegerField(default=0, verbose_name='عدد التأخرات')),
                ('total_recorded', models.PositiveIntegerField(default=0, verbose_name='المجموع المسجل')),
                ('absence_rate', models.FloatField(default=0, verbose_name='نسبة الغياب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحفظ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_stat_snapshots', to='trainees.دفعة', verbose_name='الدفعة')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_attendance_stat_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='حُفظ بواسطة')),
            ],
            options={
                'verbose_name': 'إحصائية غياب محفوظة',
                'verbose_name_plural': 'إحصائيات الغياب المحفوظة',
                'ordering': ['-year', '-month', 'program', 'specialty', 'trainee_name'],
                'indexes': [models.Index(fields=['program', 'year', 'month'], name='trainees_at_program_359432_idx'), models.Index(fields=['program', 'batch', 'specialty'], name='trainees_at_program_28699b_idx')],
                'constraints': [models.UniqueConstraint(fields=('program', 'year', 'month', 'batch', 'specialty', 'trainee_id'), name='trainees_unique_attendance_stat_snapshot_per_scope')],
            },
        ),
    ]
