# Generated by Django 5.2.11 on 2026-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0031_alter_كشفغياب_يوم_الدراسة_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='كشفغياب',
            name='يوم_الدراسة_1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(6, 'الأحد'), (0, 'الإثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت')], null=True, verbose_name='يوم الدراسة 1'),
        ),
        migrations.AlterField(
            model_name='كشفغياب',
            name='يوم_الدراسة_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(6, 'الأحد'), (0, 'الإثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت')], null=True, verbose_name='يوم الدراسة 2'),
        ),
    ]
