# Generated by Django 5.2.11 on 2026-04-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0041_cleanup_access_and_delete_legacy_log'),

    ]

    operations = [
    ]
