# Generated by ChatGPT on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainees", "0048_attendance_action_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="حضوري_أولي",
            name="بلدية_الإقامة_بالعربية",
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="بلدية الإقامة بالعربية"),
        ),
        migrations.AddField(
            model_name="تمهين",
            name="بلدية_الإقامة_بالعربية",
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="بلدية الإقامة بالعربية"),
        ),
        migrations.AddField(
            model_name="مسائي_ومعابر",
            name="بلدية_الإقامة_بالعربية",
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="بلدية الإقامة بالعربية"),
        ),
    ]
