# Generated by ChatGPT on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainees", "0049_add_residence_municipality_ar"),
    ]

    operations = [
        migrations.AddField(
            model_name="حضوري_أولي",
            name="رقم_مقرر_الفصل",
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="رقم مقرر الفصل"),
        ),
        migrations.AddField(
            model_name="تمهين",
            name="رقم_مقرر_الفصل",
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="رقم مقرر الفصل"),
        ),
        migrations.AddField(
            model_name="مسائي_ومعابر",
            name="رقم_مقرر_الفصل",
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="رقم مقرر الفصل"),
        ),
    ]
