# Generated by Django 5.2.14 on 2026-07-04 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trainees', '0056_user_attendance_summary_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['program', 'order', 'id'], 'verbose_name': 'عمود إضافي', 'verbose_name_plural': 'إضافة أعمدة'},
        ),
        migrations.AlterModelOptions(
            name='dismissaldecision',
            options={'ordering': ['program', 'decision_scope', 'is_archived', 'specialty', 'trainee_name', 'id'], 'verbose_name': 'مقرر فصل', 'verbose_name_plural': 'مقررات الفصل'},
        ),
        migrations.RemoveIndex(
            model_name='attendanceaction',
            name='trainees_at_program_3cc08f_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendanceaction',
            name='trainees_at_program_69e2b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendanceaction',
            name='trainees_at_program_4e3284_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendanceactiondeletion',
            name='trainees_at_program_5d1e32_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendanceactiondeletion',
            name='trainees_at_program_54b441_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceaction',
            new_name='trainees_at_source_ac052b_idx',
            old_name='trainees_at_src_ymt_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceactiondeletion',
            new_name='trainees_at_source_1ba6d5_idx',
            old_name='trainees_del_src_ym_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceslotcell',
            new_name='trainees_at_الكشف_i_6551eb_idx',
            old_name='trainees_sl_660889_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceslotcell',
            new_name='trainees_at_الكشف_i_57ca17_idx',
            old_name='trainees_sl_7e80cf_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceslotsheet',
            new_name='trainees_at_البرنام_9ce384_idx',
            old_name='trainees_sl_program_72cf55_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceslotsheet',
            new_name='trainees_at_البرنام_cb78ca_idx',
            old_name='trainees_sl_program_3e8621_idx',
        ),
        migrations.RenameIndex(
            model_name='comprehensiveauditlog',
            new_name='trainees_co_created_e01f4f_idx',
            old_name='trainees_co_created_dcf257_idx',
        ),
        migrations.RenameIndex(
            model_name='comprehensiveauditlog',
            new_name='trainees_co_action_ca5a85_idx',
            old_name='trainees_co_action_363f55_idx',
        ),
        migrations.RenameIndex(
            model_name='comprehensiveauditlog',
            new_name='trainees_co_view_na_4ebbe3_idx',
            old_name='trainees_co_view_na_c03e65_idx',
        ),
        migrations.RenameIndex(
            model_name='comprehensiveauditlog',
            new_name='trainees_co_model_l_ff6016_idx',
            old_name='trainees_co_model_l_41cc1f_idx',
        ),
        migrations.RenameIndex(
            model_name='dismissaldecision',
            new_name='trainees_di_program_d860a5_idx',
            old_name='trainees_di_program_1c2215_idx',
        ),
        migrations.RenameIndex(
            model_name='dismissaldecision',
            new_name='trainees_di_program_c6f465_idx',
            old_name='trainees_di_program_4437d0_idx',
        ),
        migrations.RenameIndex(
            model_name='dismissaldecision',
            new_name='trainees_di_program_34a763_idx',
            old_name='trainees_di_program_41b6ac_idx',
        ),
        migrations.RenameIndex(
            model_name='dismissaldecision',
            new_name='trainees_di_trainee_844f82_idx',
            old_name='trainees_di_trainee_c872d5_idx',
        ),
        migrations.RenameIndex(
            model_name='sanctionrecord',
            new_name='trainees_sa_program_6e84a4_idx',
            old_name='trainees_sa_program_d2701f_idx',
        ),
        migrations.RenameIndex(
            model_name='sanctionrecord',
            new_name='trainees_sa_program_73c9dc_idx',
            old_name='trainees_sa_program_6b6924_idx',
        ),
        migrations.RenameIndex(
            model_name='sanctionrecord',
            new_name='trainees_sa_program_eb0eff_idx',
            old_name='trainees_sa_program_eac76f_idx',
        ),
        migrations.RenameIndex(
            model_name='summonsrecord',
            new_name='trainees_su_program_fe0d7c_idx',
            old_name='trainees_su_program_4c1894_idx',
        ),
        migrations.RenameIndex(
            model_name='summonsrecord',
            new_name='trainees_su_program_44df5a_idx',
            old_name='trainees_su_program_08e17c_idx',
        ),
        migrations.RenameIndex(
            model_name='summonsrecord',
            new_name='trainees_su_program_732901_idx',
            old_name='trainees_su_program_c3c31b_idx',
        ),
        migrations.RenameIndex(
            model_name='userattendancesummaryarchive',
            new_name='trainees_us_program_6ca577_idx',
            old_name='trainees_us_program_54b03c_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'دخول'), ('logout', 'خروج'), ('login_failed', 'محاولة دخول فاشلة'), ('view', 'عرض'), ('add', 'إضافة'), ('change', 'تعديل'), ('delete', 'حذف'), ('export', 'تصدير'), ('access_denied', 'منع وصول')], max_length=20, verbose_name='الإجراء'),
        ),
        migrations.AddIndex(
            model_name='attendanceaction',
            index=models.Index(fields=['source', 'program', 'status'], name='trainees_at_source_1026e3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceaction',
            index=models.Index(fields=['source', 'program', 'is_archived'], name='trainees_at_source_23697a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceactiondeletion',
            index=models.Index(fields=['source', 'program', 'action_type'], name='trainees_at_source_b4bd4b_idx'),
        ),
    ]
